/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  URLTitleRequest,
  URLTitleResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Fetch a URL and extract its page title.
 * @summary Get Url Title
 */
export const getUrlTitleApiV1UrlTitlePost = (
    uRLTitleRequest: URLTitleRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<URLTitleResponse>(
      {url: `/api/v1/url/title`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: uRLTitleRequest, signal
    },
      );
    }
  


export const getGetUrlTitleApiV1UrlTitlePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUrlTitleApiV1UrlTitlePost>>, TError,{data: URLTitleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getUrlTitleApiV1UrlTitlePost>>, TError,{data: URLTitleRequest}, TContext> => {

const mutationKey = ['getUrlTitleApiV1UrlTitlePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUrlTitleApiV1UrlTitlePost>>, {data: URLTitleRequest}> = (props) => {
          const {data} = props ?? {};

          return  getUrlTitleApiV1UrlTitlePost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetUrlTitleApiV1UrlTitlePostMutationResult = NonNullable<Awaited<ReturnType<typeof getUrlTitleApiV1UrlTitlePost>>>
    export type GetUrlTitleApiV1UrlTitlePostMutationBody = URLTitleRequest
    export type GetUrlTitleApiV1UrlTitlePostMutationError = HTTPValidationError

    /**
 * @summary Get Url Title
 */
export const useGetUrlTitleApiV1UrlTitlePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUrlTitleApiV1UrlTitlePost>>, TError,{data: URLTitleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUrlTitleApiV1UrlTitlePost>>,
        TError,
        {data: URLTitleRequest},
        TContext
      > => {
      return useMutation(getGetUrlTitleApiV1UrlTitlePostMutationOptions(options), queryClient);
    }
    