/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppRoutersBackupImportResponse,
  BodyImportBackupApiV1BackupImportPost,
  HTTPValidationError,
  SnapshotListResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Export all user data as a JSON file.

Returns a downloadable JSON file with all tasks, domains, and preferences.
 * @summary Export Backup
 */
export const exportBackupApiV1BackupExportGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/backup/export`, method: 'GET', signal
    },
      );
    }
  



export const getExportBackupApiV1BackupExportGetQueryKey = () => {
    return [
    `/api/v1/backup/export`
    ] as const;
    }

    
export const getExportBackupApiV1BackupExportGetQueryOptions = <TData = Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportBackupApiV1BackupExportGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>> = ({ signal }) => exportBackupApiV1BackupExportGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportBackupApiV1BackupExportGetQueryResult = NonNullable<Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>>
export type ExportBackupApiV1BackupExportGetQueryError = unknown


export function useExportBackupApiV1BackupExportGet<TData = Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportBackupApiV1BackupExportGet<TData = Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportBackupApiV1BackupExportGet<TData = Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Backup
 */

export function useExportBackupApiV1BackupExportGet<TData = Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportBackupApiV1BackupExportGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportBackupApiV1BackupExportGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Import user data from a backup JSON file.

WARNING: This will replace all existing data!
 * @summary Import Backup
 */
export const importBackupApiV1BackupImportPost = (
    bodyImportBackupApiV1BackupImportPost: BodyImportBackupApiV1BackupImportPost,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyImportBackupApiV1BackupImportPost.file);

      return apiClient<AppRoutersBackupImportResponse>(
      {url: `/api/v1/backup/import`, method: 'POST',
       data: formData, signal
    },
      );
    }
  


export const getImportBackupApiV1BackupImportPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importBackupApiV1BackupImportPost>>, TError,{data: BodyImportBackupApiV1BackupImportPost}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof importBackupApiV1BackupImportPost>>, TError,{data: BodyImportBackupApiV1BackupImportPost}, TContext> => {

const mutationKey = ['importBackupApiV1BackupImportPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importBackupApiV1BackupImportPost>>, {data: BodyImportBackupApiV1BackupImportPost}> = (props) => {
          const {data} = props ?? {};

          return  importBackupApiV1BackupImportPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ImportBackupApiV1BackupImportPostMutationResult = NonNullable<Awaited<ReturnType<typeof importBackupApiV1BackupImportPost>>>
    export type ImportBackupApiV1BackupImportPostMutationBody = BodyImportBackupApiV1BackupImportPost
    export type ImportBackupApiV1BackupImportPostMutationError = HTTPValidationError

    /**
 * @summary Import Backup
 */
export const useImportBackupApiV1BackupImportPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importBackupApiV1BackupImportPost>>, TError,{data: BodyImportBackupApiV1BackupImportPost}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importBackupApiV1BackupImportPost>>,
        TError,
        {data: BodyImportBackupApiV1BackupImportPost},
        TContext
      > => {
      return useMutation(getImportBackupApiV1BackupImportPostMutationOptions(options), queryClient);
    }
    /**
 * List all snapshots with enabled state.
 * @summary List Snapshots
 */
export const listSnapshotsApiV1BackupSnapshotsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<SnapshotListResponse>(
      {url: `/api/v1/backup/snapshots`, method: 'GET', signal
    },
      );
    }
  



export const getListSnapshotsApiV1BackupSnapshotsGetQueryKey = () => {
    return [
    `/api/v1/backup/snapshots`
    ] as const;
    }

    
export const getListSnapshotsApiV1BackupSnapshotsGetQueryOptions = <TData = Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSnapshotsApiV1BackupSnapshotsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>> = ({ signal }) => listSnapshotsApiV1BackupSnapshotsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSnapshotsApiV1BackupSnapshotsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>>
export type ListSnapshotsApiV1BackupSnapshotsGetQueryError = unknown


export function useListSnapshotsApiV1BackupSnapshotsGet<TData = Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>,
          TError,
          Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSnapshotsApiV1BackupSnapshotsGet<TData = Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>,
          TError,
          Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSnapshotsApiV1BackupSnapshotsGet<TData = Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Snapshots
 */

export function useListSnapshotsApiV1BackupSnapshotsGet<TData = Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSnapshotsApiV1BackupSnapshotsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSnapshotsApiV1BackupSnapshotsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a manual snapshot.
 * @summary Create Manual Snapshot
 */
export const createManualSnapshotApiV1BackupSnapshotsPost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/backup/snapshots`, method: 'POST', signal
    },
      );
    }
  


export const getCreateManualSnapshotApiV1BackupSnapshotsPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createManualSnapshotApiV1BackupSnapshotsPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createManualSnapshotApiV1BackupSnapshotsPost>>, TError,void, TContext> => {

const mutationKey = ['createManualSnapshotApiV1BackupSnapshotsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createManualSnapshotApiV1BackupSnapshotsPost>>, void> = () => {
          

          return  createManualSnapshotApiV1BackupSnapshotsPost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateManualSnapshotApiV1BackupSnapshotsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createManualSnapshotApiV1BackupSnapshotsPost>>>
    
    export type CreateManualSnapshotApiV1BackupSnapshotsPostMutationError = unknown

    /**
 * @summary Create Manual Snapshot
 */
export const useCreateManualSnapshotApiV1BackupSnapshotsPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createManualSnapshotApiV1BackupSnapshotsPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createManualSnapshotApiV1BackupSnapshotsPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCreateManualSnapshotApiV1BackupSnapshotsPostMutationOptions(options), queryClient);
    }
    /**
 * Toggle automatic snapshots on/off.
 * @summary Toggle Snapshots
 */
export const toggleSnapshotsApiV1BackupSnapshotsEnabledPut = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/backup/snapshots/enabled`, method: 'PUT', signal
    },
      );
    }
  


export const getToggleSnapshotsApiV1BackupSnapshotsEnabledPutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleSnapshotsApiV1BackupSnapshotsEnabledPut>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleSnapshotsApiV1BackupSnapshotsEnabledPut>>, TError,void, TContext> => {

const mutationKey = ['toggleSnapshotsApiV1BackupSnapshotsEnabledPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleSnapshotsApiV1BackupSnapshotsEnabledPut>>, void> = () => {
          

          return  toggleSnapshotsApiV1BackupSnapshotsEnabledPut()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleSnapshotsApiV1BackupSnapshotsEnabledPutMutationResult = NonNullable<Awaited<ReturnType<typeof toggleSnapshotsApiV1BackupSnapshotsEnabledPut>>>
    
    export type ToggleSnapshotsApiV1BackupSnapshotsEnabledPutMutationError = unknown

    /**
 * @summary Toggle Snapshots
 */
export const useToggleSnapshotsApiV1BackupSnapshotsEnabledPut = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleSnapshotsApiV1BackupSnapshotsEnabledPut>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleSnapshotsApiV1BackupSnapshotsEnabledPut>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getToggleSnapshotsApiV1BackupSnapshotsEnabledPutMutationOptions(options), queryClient);
    }
    /**
 * Download a snapshot as a JSON file.
 * @summary Download Snapshot
 */
export const downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet = (
    snapshotId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/backup/snapshots/${snapshotId}/download`, method: 'GET', signal
    },
      );
    }
  



export const getDownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGetQueryKey = (snapshotId: number,) => {
    return [
    `/api/v1/backup/snapshots/${snapshotId}/download`
    ] as const;
    }

    
export const getDownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError = HTTPValidationError>(snapshotId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGetQueryKey(snapshotId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>> = ({ signal }) => downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet(snapshotId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(snapshotId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>>
export type DownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGetQueryError = HTTPValidationError


export function useDownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet<TData = Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError = HTTPValidationError>(
 snapshotId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet<TData = Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError = HTTPValidationError>(
 snapshotId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet<TData = Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError = HTTPValidationError>(
 snapshotId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Snapshot
 */

export function useDownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet<TData = Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError = HTTPValidationError>(
 snapshotId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadSnapshotApiV1BackupSnapshotsSnapshotIdDownloadGetQueryOptions(snapshotId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Restore user data from a snapshot.
 * @summary Restore Snapshot
 */
export const restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost = (
    snapshotId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/backup/snapshots/${snapshotId}/restore`, method: 'POST', signal
    },
      );
    }
  


export const getRestoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost>>, TError,{snapshotId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost>>, TError,{snapshotId: number}, TContext> => {

const mutationKey = ['restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost>>, {snapshotId: number}> = (props) => {
          const {snapshotId} = props ?? {};

          return  restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost(snapshotId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RestoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePostMutationResult = NonNullable<Awaited<ReturnType<typeof restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost>>>
    
    export type RestoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePostMutationError = HTTPValidationError

    /**
 * @summary Restore Snapshot
 */
export const useRestoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost>>, TError,{snapshotId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePost>>,
        TError,
        {snapshotId: number},
        TContext
      > => {
      return useMutation(getRestoreSnapshotApiV1BackupSnapshotsSnapshotIdRestorePostMutationOptions(options), queryClient);
    }
    /**
 * Delete a single snapshot.
 * @summary Delete Snapshot
 */
export const deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete = (
    snapshotId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/backup/snapshots/${snapshotId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteSnapshotApiV1BackupSnapshotsSnapshotIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete>>, TError,{snapshotId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete>>, TError,{snapshotId: number}, TContext> => {

const mutationKey = ['deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete>>, {snapshotId: number}> = (props) => {
          const {snapshotId} = props ?? {};

          return  deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete(snapshotId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSnapshotApiV1BackupSnapshotsSnapshotIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete>>>
    
    export type DeleteSnapshotApiV1BackupSnapshotsSnapshotIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Snapshot
 */
export const useDeleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete>>, TError,{snapshotId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSnapshotApiV1BackupSnapshotsSnapshotIdDelete>>,
        TError,
        {snapshotId: number},
        TContext
      > => {
      return useMutation(getDeleteSnapshotApiV1BackupSnapshotsSnapshotIdDeleteMutationOptions(options), queryClient);
    }
    