/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CSRFTokenResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Return the CSRF token for the current session.
 * @summary Get Csrf
 */
export const getCsrfApiV1CsrfGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<CSRFTokenResponse>(
      {url: `/api/v1/csrf`, method: 'GET', signal
    },
      );
    }
  



export const getGetCsrfApiV1CsrfGetQueryKey = () => {
    return [
    `/api/v1/csrf`
    ] as const;
    }

    
export const getGetCsrfApiV1CsrfGetQueryOptions = <TData = Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCsrfApiV1CsrfGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>> = ({ signal }) => getCsrfApiV1CsrfGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCsrfApiV1CsrfGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>>
export type GetCsrfApiV1CsrfGetQueryError = unknown


export function useGetCsrfApiV1CsrfGet<TData = Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>,
          TError,
          Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCsrfApiV1CsrfGet<TData = Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>,
          TError,
          Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCsrfApiV1CsrfGet<TData = Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Csrf
 */

export function useGetCsrfApiV1CsrfGet<TData = Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCsrfApiV1CsrfGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCsrfApiV1CsrfGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




