/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CalendarResponse,
  CalendarSelectionsRequest,
  EventResponse,
  GetEventsApiV1EventsGetParams,
  HTTPValidationError,
  ProjectResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Get all projects.
 * @summary Get Projects
 */
export const getProjectsApiV1ProjectsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ProjectResponse[]>(
      {url: `/api/v1/projects`, method: 'GET', signal
    },
      );
    }
  



export const getGetProjectsApiV1ProjectsGetQueryKey = () => {
    return [
    `/api/v1/projects`
    ] as const;
    }

    
export const getGetProjectsApiV1ProjectsGetQueryOptions = <TData = Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectsApiV1ProjectsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>> = ({ signal }) => getProjectsApiV1ProjectsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectsApiV1ProjectsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>>
export type GetProjectsApiV1ProjectsGetQueryError = unknown


export function useGetProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>,
          TError,
          Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>,
          TError,
          Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Projects
 */

export function useGetProjectsApiV1ProjectsGet<TData = Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsApiV1ProjectsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectsApiV1ProjectsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get calendar events for enabled calendars.
 * @summary Get Events
 */
export const getEventsApiV1EventsGet = (
    params?: GetEventsApiV1EventsGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<EventResponse[]>(
      {url: `/api/v1/events`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetEventsApiV1EventsGetQueryKey = (params?: GetEventsApiV1EventsGetParams,) => {
    return [
    `/api/v1/events`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetEventsApiV1EventsGetQueryOptions = <TData = Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError = HTTPValidationError>(params?: GetEventsApiV1EventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventsApiV1EventsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventsApiV1EventsGet>>> = ({ signal }) => getEventsApiV1EventsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventsApiV1EventsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEventsApiV1EventsGet>>>
export type GetEventsApiV1EventsGetQueryError = HTTPValidationError


export function useGetEventsApiV1EventsGet<TData = Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetEventsApiV1EventsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsApiV1EventsGet>>,
          TError,
          Awaited<ReturnType<typeof getEventsApiV1EventsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventsApiV1EventsGet<TData = Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError = HTTPValidationError>(
 params?: GetEventsApiV1EventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventsApiV1EventsGet>>,
          TError,
          Awaited<ReturnType<typeof getEventsApiV1EventsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventsApiV1EventsGet<TData = Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError = HTTPValidationError>(
 params?: GetEventsApiV1EventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Events
 */

export function useGetEventsApiV1EventsGet<TData = Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError = HTTPValidationError>(
 params?: GetEventsApiV1EventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventsApiV1EventsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventsApiV1EventsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get all available calendars with their enabled status.
 * @summary Get Calendars
 */
export const getCalendarsApiV1CalendarsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<CalendarResponse[]>(
      {url: `/api/v1/calendars`, method: 'GET', signal
    },
      );
    }
  



export const getGetCalendarsApiV1CalendarsGetQueryKey = () => {
    return [
    `/api/v1/calendars`
    ] as const;
    }

    
export const getGetCalendarsApiV1CalendarsGetQueryOptions = <TData = Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCalendarsApiV1CalendarsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>> = ({ signal }) => getCalendarsApiV1CalendarsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCalendarsApiV1CalendarsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>>
export type GetCalendarsApiV1CalendarsGetQueryError = unknown


export function useGetCalendarsApiV1CalendarsGet<TData = Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>,
          TError,
          Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarsApiV1CalendarsGet<TData = Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>,
          TError,
          Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarsApiV1CalendarsGet<TData = Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Calendars
 */

export function useGetCalendarsApiV1CalendarsGet<TData = Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarsApiV1CalendarsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCalendarsApiV1CalendarsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Toggle a calendar's enabled status.
 * @summary Toggle Calendar
 */
export const toggleCalendarApiV1CalendarsCalendarIdTogglePost = (
    calendarId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/calendars/${calendarId}/toggle`, method: 'POST', signal
    },
      );
    }
  


export const getToggleCalendarApiV1CalendarsCalendarIdTogglePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleCalendarApiV1CalendarsCalendarIdTogglePost>>, TError,{calendarId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleCalendarApiV1CalendarsCalendarIdTogglePost>>, TError,{calendarId: string}, TContext> => {

const mutationKey = ['toggleCalendarApiV1CalendarsCalendarIdTogglePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleCalendarApiV1CalendarsCalendarIdTogglePost>>, {calendarId: string}> = (props) => {
          const {calendarId} = props ?? {};

          return  toggleCalendarApiV1CalendarsCalendarIdTogglePost(calendarId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleCalendarApiV1CalendarsCalendarIdTogglePostMutationResult = NonNullable<Awaited<ReturnType<typeof toggleCalendarApiV1CalendarsCalendarIdTogglePost>>>
    
    export type ToggleCalendarApiV1CalendarsCalendarIdTogglePostMutationError = HTTPValidationError

    /**
 * @summary Toggle Calendar
 */
export const useToggleCalendarApiV1CalendarsCalendarIdTogglePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleCalendarApiV1CalendarsCalendarIdTogglePost>>, TError,{calendarId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleCalendarApiV1CalendarsCalendarIdTogglePost>>,
        TError,
        {calendarId: string},
        TContext
      > => {
      return useMutation(getToggleCalendarApiV1CalendarsCalendarIdTogglePostMutationOptions(options), queryClient);
    }
    /**
 * Set which calendars are enabled (from wizard).
 * @summary Set Calendar Selections
 */
export const setCalendarSelectionsApiV1CalendarsSelectionsPost = (
    calendarSelectionsRequest: CalendarSelectionsRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/calendars/selections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: calendarSelectionsRequest, signal
    },
      );
    }
  


export const getSetCalendarSelectionsApiV1CalendarsSelectionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setCalendarSelectionsApiV1CalendarsSelectionsPost>>, TError,{data: CalendarSelectionsRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof setCalendarSelectionsApiV1CalendarsSelectionsPost>>, TError,{data: CalendarSelectionsRequest}, TContext> => {

const mutationKey = ['setCalendarSelectionsApiV1CalendarsSelectionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setCalendarSelectionsApiV1CalendarsSelectionsPost>>, {data: CalendarSelectionsRequest}> = (props) => {
          const {data} = props ?? {};

          return  setCalendarSelectionsApiV1CalendarsSelectionsPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SetCalendarSelectionsApiV1CalendarsSelectionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof setCalendarSelectionsApiV1CalendarsSelectionsPost>>>
    export type SetCalendarSelectionsApiV1CalendarsSelectionsPostMutationBody = CalendarSelectionsRequest
    export type SetCalendarSelectionsApiV1CalendarsSelectionsPostMutationError = HTTPValidationError

    /**
 * @summary Set Calendar Selections
 */
export const useSetCalendarSelectionsApiV1CalendarsSelectionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setCalendarSelectionsApiV1CalendarsSelectionsPost>>, TError,{data: CalendarSelectionsRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setCalendarSelectionsApiV1CalendarsSelectionsPost>>,
        TError,
        {data: CalendarSelectionsRequest},
        TContext
      > => {
      return useMutation(getSetCalendarSelectionsApiV1CalendarsSelectionsPostMutationOptions(options), queryClient);
    }
    