"""add calendar feed token

Revision ID: 216c48a55179
Revises: eb49fa918b23
Create Date: 2026-03-02 16:02:23.406985+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "216c48a55179"
down_revision: str | None = "eb49fa918b23"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_preferences", sa.Column("feed_token", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_user_preferences_feed_token"), "user_preferences", ["feed_token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_preferences_feed_token"), table_name="user_preferences")
    op.drop_column("user_preferences", "feed_token")
    # ### end Alembic commands ###
