"""add_reminder_index

Revision ID: 1e2661d9806d
Revises: 1a205ae8f2d9
Create Date: 2026-03-06 12:06:17.174581+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e2661d9806d"
down_revision: str | None = "1a205ae8f2d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_task_reminder", "tasks", ["reminder_sent_at", "reminder_minutes_before", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_reminder", table_name="tasks")
    # ### end Alembic commands ###
