"""add reminder_minutes_before to tasks

Revision ID: e9acd97a9964
Revises: 37388bf4b212
Create Date: 2026-03-04 20:54:48.463067+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9acd97a9964"
down_revision: str | None = "37388bf4b212"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("reminder_minutes_before", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "reminder_minutes_before")
    # ### end Alembic commands ###
