"""remove_gcal_sync_all_day

Revision ID: 22fd714eb4ad
Revises: d4792085f030
Create Date: 2026-02-02 12:07:23.977961+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22fd714eb4ad"
down_revision: str | None = "d4792085f030"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_preferences", "gcal_sync_all_day")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_preferences",
        sa.Column(
            "gcal_sync_all_day", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
