"""rename clarity values executable to clear and exploratory to open

Revision ID: 19c84fcb100b
Revises: f70641cd1228
Create Date: 2026-02-06 18:07:40.620916+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19c84fcb100b"
down_revision: str | None = "f70641cd1228"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename clarity values: executable → clear, exploratory → open
    op.execute("UPDATE tasks SET clarity = 'clear' WHERE clarity = 'executable'")
    op.execute("UPDATE tasks SET clarity = 'open' WHERE clarity = 'exploratory'")
    # defined stays as-is
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert clarity values: clear → executable, open → exploratory
    op.execute("UPDATE tasks SET clarity = 'executable' WHERE clarity = 'clear'")
    op.execute("UPDATE tasks SET clarity = 'exploratory' WHERE clarity = 'open'")
    # ### end Alembic commands ###
