"""add analytics composite indexes

Revision ID: b1c305c4bc97
Revises: ea143101df03
Create Date: 2026-02-25 22:17:28.364607+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1c305c4bc97"
down_revision: str | None = "ea143101df03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_instance_user_status_completed", "task_instances", ["user_id", "status", "completed_at"], unique=False
    )
    op.create_index("ix_task_user_status_completed", "tasks", ["user_id", "status", "completed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_user_status_completed", table_name="tasks")
    op.drop_index("ix_instance_user_status_completed", table_name="task_instances")
    # ### end Alembic commands ###
