"""add_activity_log_table

Revision ID: d0b8784b5b22
Revises: 216c48a55179
Create Date: 2026-03-04 00:41:53.409200+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0b8784b5b22"
down_revision: str | None = "216c48a55179"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column("domain_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("field_name", sa.String(length=50), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("batch_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["domain_id"], ["domains.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["instance_id"], ["task_instances.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_activity_log_user_created", "activity_log", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_activity_log_user_id"), "activity_log", ["user_id"], unique=False)
    op.create_index("ix_activity_log_user_task", "activity_log", ["user_id", "task_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activity_log_user_task", table_name="activity_log")
    op.drop_index(op.f("ix_activity_log_user_id"), table_name="activity_log")
    op.drop_index("ix_activity_log_user_created", table_name="activity_log")
    op.drop_table("activity_log")
    # ### end Alembic commands ###
