/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.82
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FeedDisableResponse,
  FeedEnableResponse,
  FeedRegenerateResponse,
  FeedStatusResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Get calendar feed status for the current user.
 * @summary Get Feed Status
 */
export const getFeedStatusApiV1CalendarFeedStatusGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<FeedStatusResponse>(
      {url: `/api/v1/calendar-feed/status`, method: 'GET', signal
    },
      );
    }
  



export const getGetFeedStatusApiV1CalendarFeedStatusGetQueryKey = () => {
    return [
    `/api/v1/calendar-feed/status`
    ] as const;
    }

    
export const getGetFeedStatusApiV1CalendarFeedStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeedStatusApiV1CalendarFeedStatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>> = ({ signal }) => getFeedStatusApiV1CalendarFeedStatusGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFeedStatusApiV1CalendarFeedStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>>
export type GetFeedStatusApiV1CalendarFeedStatusGetQueryError = unknown


export function useGetFeedStatusApiV1CalendarFeedStatusGet<TData = Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeedStatusApiV1CalendarFeedStatusGet<TData = Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeedStatusApiV1CalendarFeedStatusGet<TData = Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Feed Status
 */

export function useGetFeedStatusApiV1CalendarFeedStatusGet<TData = Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeedStatusApiV1CalendarFeedStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFeedStatusApiV1CalendarFeedStatusGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Enable the calendar feed and generate a token.
 * @summary Enable Feed
 */
export const enableFeedApiV1CalendarFeedEnablePost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<FeedEnableResponse>(
      {url: `/api/v1/calendar-feed/enable`, method: 'POST', signal
    },
      );
    }
  


export const getEnableFeedApiV1CalendarFeedEnablePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableFeedApiV1CalendarFeedEnablePost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof enableFeedApiV1CalendarFeedEnablePost>>, TError,void, TContext> => {

const mutationKey = ['enableFeedApiV1CalendarFeedEnablePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enableFeedApiV1CalendarFeedEnablePost>>, void> = () => {
          

          return  enableFeedApiV1CalendarFeedEnablePost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EnableFeedApiV1CalendarFeedEnablePostMutationResult = NonNullable<Awaited<ReturnType<typeof enableFeedApiV1CalendarFeedEnablePost>>>
    
    export type EnableFeedApiV1CalendarFeedEnablePostMutationError = unknown

    /**
 * @summary Enable Feed
 */
export const useEnableFeedApiV1CalendarFeedEnablePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableFeedApiV1CalendarFeedEnablePost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enableFeedApiV1CalendarFeedEnablePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getEnableFeedApiV1CalendarFeedEnablePostMutationOptions(options), queryClient);
    }
    /**
 * Disable the calendar feed and clear the token.
 * @summary Disable Feed
 */
export const disableFeedApiV1CalendarFeedDisablePost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<FeedDisableResponse>(
      {url: `/api/v1/calendar-feed/disable`, method: 'POST', signal
    },
      );
    }
  


export const getDisableFeedApiV1CalendarFeedDisablePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableFeedApiV1CalendarFeedDisablePost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof disableFeedApiV1CalendarFeedDisablePost>>, TError,void, TContext> => {

const mutationKey = ['disableFeedApiV1CalendarFeedDisablePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disableFeedApiV1CalendarFeedDisablePost>>, void> = () => {
          

          return  disableFeedApiV1CalendarFeedDisablePost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DisableFeedApiV1CalendarFeedDisablePostMutationResult = NonNullable<Awaited<ReturnType<typeof disableFeedApiV1CalendarFeedDisablePost>>>
    
    export type DisableFeedApiV1CalendarFeedDisablePostMutationError = unknown

    /**
 * @summary Disable Feed
 */
export const useDisableFeedApiV1CalendarFeedDisablePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableFeedApiV1CalendarFeedDisablePost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disableFeedApiV1CalendarFeedDisablePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDisableFeedApiV1CalendarFeedDisablePostMutationOptions(options), queryClient);
    }
    /**
 * Generate a new feed token. The old URL stops working immediately.
 * @summary Regenerate Feed
 */
export const regenerateFeedApiV1CalendarFeedRegeneratePost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<FeedRegenerateResponse>(
      {url: `/api/v1/calendar-feed/regenerate`, method: 'POST', signal
    },
      );
    }
  


export const getRegenerateFeedApiV1CalendarFeedRegeneratePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof regenerateFeedApiV1CalendarFeedRegeneratePost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof regenerateFeedApiV1CalendarFeedRegeneratePost>>, TError,void, TContext> => {

const mutationKey = ['regenerateFeedApiV1CalendarFeedRegeneratePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof regenerateFeedApiV1CalendarFeedRegeneratePost>>, void> = () => {
          

          return  regenerateFeedApiV1CalendarFeedRegeneratePost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegenerateFeedApiV1CalendarFeedRegeneratePostMutationResult = NonNullable<Awaited<ReturnType<typeof regenerateFeedApiV1CalendarFeedRegeneratePost>>>
    
    export type RegenerateFeedApiV1CalendarFeedRegeneratePostMutationError = unknown

    /**
 * @summary Regenerate Feed
 */
export const useRegenerateFeedApiV1CalendarFeedRegeneratePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof regenerateFeedApiV1CalendarFeedRegeneratePost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof regenerateFeedApiV1CalendarFeedRegeneratePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRegenerateFeedApiV1CalendarFeedRegeneratePostMutationOptions(options), queryClient);
    }
    