/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AllDataResponse,
  AppRoutersTasksTaskResponse,
  BatchUpdateTasksRequest,
  HTTPValidationError,
  ListTasksApiV1TasksGetParams,
  TaskCreate,
  TaskUpdate,
  ToggleCompleteRequest
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Get tasks with optional filtering.
 * @summary List Tasks
 */
export const listTasksApiV1TasksGet = (
    params?: ListTasksApiV1TasksGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AppRoutersTasksTaskResponse[]>(
      {url: `/api/v1/tasks`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListTasksApiV1TasksGetQueryKey = (params?: ListTasksApiV1TasksGetParams,) => {
    return [
    `/api/v1/tasks`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListTasksApiV1TasksGetQueryOptions = <TData = Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError = HTTPValidationError>(params?: ListTasksApiV1TasksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTasksApiV1TasksGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTasksApiV1TasksGet>>> = ({ signal }) => listTasksApiV1TasksGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTasksApiV1TasksGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTasksApiV1TasksGet>>>
export type ListTasksApiV1TasksGetQueryError = HTTPValidationError


export function useListTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError = HTTPValidationError>(
 params: undefined |  ListTasksApiV1TasksGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTasksApiV1TasksGet>>,
          TError,
          Awaited<ReturnType<typeof listTasksApiV1TasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError = HTTPValidationError>(
 params?: ListTasksApiV1TasksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTasksApiV1TasksGet>>,
          TError,
          Awaited<ReturnType<typeof listTasksApiV1TasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError = HTTPValidationError>(
 params?: ListTasksApiV1TasksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Tasks
 */

export function useListTasksApiV1TasksGet<TData = Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError = HTTPValidationError>(
 params?: ListTasksApiV1TasksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksApiV1TasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTasksApiV1TasksGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new task.
 * @summary Create Task
 */
export const createTaskApiV1TasksPost = (
    taskCreate: TaskCreate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AppRoutersTasksTaskResponse>(
      {url: `/api/v1/tasks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: taskCreate, signal
    },
      );
    }
  


export const getCreateTaskApiV1TasksPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,{data: TaskCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,{data: TaskCreate}, TContext> => {

const mutationKey = ['createTaskApiV1TasksPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, {data: TaskCreate}> = (props) => {
          const {data} = props ?? {};

          return  createTaskApiV1TasksPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskApiV1TasksPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>>
    export type CreateTaskApiV1TasksPostMutationBody = TaskCreate
    export type CreateTaskApiV1TasksPostMutationError = HTTPValidationError

    /**
 * @summary Create Task
 */
export const useCreateTaskApiV1TasksPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskApiV1TasksPost>>, TError,{data: TaskCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTaskApiV1TasksPost>>,
        TError,
        {data: TaskCreate},
        TContext
      > => {
      return useMutation(getCreateTaskApiV1TasksPostMutationOptions(options), queryClient);
    }
    /**
 * Get all task titles/descriptions and domain names for the user.

Used by the client when enabling/disabling encryption to encrypt/decrypt
all data in a single batch operation.
 * @summary Get All Content
 */
export const getAllContentApiV1TasksAllContentGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<AllDataResponse>(
      {url: `/api/v1/tasks/all-content`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllContentApiV1TasksAllContentGetQueryKey = () => {
    return [
    `/api/v1/tasks/all-content`
    ] as const;
    }

    
export const getGetAllContentApiV1TasksAllContentGetQueryOptions = <TData = Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllContentApiV1TasksAllContentGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>> = ({ signal }) => getAllContentApiV1TasksAllContentGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllContentApiV1TasksAllContentGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>>
export type GetAllContentApiV1TasksAllContentGetQueryError = unknown


export function useGetAllContentApiV1TasksAllContentGet<TData = Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>,
          TError,
          Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllContentApiV1TasksAllContentGet<TData = Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>,
          TError,
          Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllContentApiV1TasksAllContentGet<TData = Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get All Content
 */

export function useGetAllContentApiV1TasksAllContentGet<TData = Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllContentApiV1TasksAllContentGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllContentApiV1TasksAllContentGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get a single task by ID.
 * @summary Get Task
 */
export const getTaskApiV1TasksTaskIdGet = (
    taskId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AppRoutersTasksTaskResponse>(
      {url: `/api/v1/tasks/${taskId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetTaskApiV1TasksTaskIdGetQueryKey = (taskId: number,) => {
    return [
    `/api/v1/tasks/${taskId}`
    ] as const;
    }

    
export const getGetTaskApiV1TasksTaskIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = HTTPValidationError>(taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskApiV1TasksTaskIdGetQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>> = ({ signal }) => getTaskApiV1TasksTaskIdGet(taskId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskApiV1TasksTaskIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>>
export type GetTaskApiV1TasksTaskIdGetQueryError = HTTPValidationError


export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Task
 */

export function useGetTaskApiV1TasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskApiV1TasksTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskApiV1TasksTaskIdGetQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a task.
 * @summary Update Task
 */
export const updateTaskApiV1TasksTaskIdPut = (
    taskId: number,
    taskUpdate: TaskUpdate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AppRoutersTasksTaskResponse>(
      {url: `/api/v1/tasks/${taskId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: taskUpdate, signal
    },
      );
    }
  


export const getUpdateTaskApiV1TasksTaskIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPut>>, TError,{taskId: number;data: TaskUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPut>>, TError,{taskId: number;data: TaskUpdate}, TContext> => {

const mutationKey = ['updateTaskApiV1TasksTaskIdPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPut>>, {taskId: number;data: TaskUpdate}> = (props) => {
          const {taskId,data} = props ?? {};

          return  updateTaskApiV1TasksTaskIdPut(taskId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskApiV1TasksTaskIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPut>>>
    export type UpdateTaskApiV1TasksTaskIdPutMutationBody = TaskUpdate
    export type UpdateTaskApiV1TasksTaskIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Task
 */
export const useUpdateTaskApiV1TasksTaskIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPut>>, TError,{taskId: number;data: TaskUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTaskApiV1TasksTaskIdPut>>,
        TError,
        {taskId: number;data: TaskUpdate},
        TContext
      > => {
      return useMutation(getUpdateTaskApiV1TasksTaskIdPutMutationOptions(options), queryClient);
    }
    /**
 * Archive a task (soft delete).
 * @summary Delete Task
 */
export const deleteTaskApiV1TasksTaskIdDelete = (
    taskId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<void>(
      {url: `/api/v1/tasks/${taskId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteTaskApiV1TasksTaskIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTaskApiV1TasksTaskIdDelete>>, TError,{taskId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteTaskApiV1TasksTaskIdDelete>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['deleteTaskApiV1TasksTaskIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTaskApiV1TasksTaskIdDelete>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  deleteTaskApiV1TasksTaskIdDelete(taskId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTaskApiV1TasksTaskIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTaskApiV1TasksTaskIdDelete>>>
    
    export type DeleteTaskApiV1TasksTaskIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Task
 */
export const useDeleteTaskApiV1TasksTaskIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTaskApiV1TasksTaskIdDelete>>, TError,{taskId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTaskApiV1TasksTaskIdDelete>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getDeleteTaskApiV1TasksTaskIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Restore an archived task back to pending status.
 * @summary Restore Task
 */
export const restoreTaskApiV1TasksTaskIdRestorePost = (
    taskId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AppRoutersTasksTaskResponse>(
      {url: `/api/v1/tasks/${taskId}/restore`, method: 'POST', signal
    },
      );
    }
  


export const getRestoreTaskApiV1TasksTaskIdRestorePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreTaskApiV1TasksTaskIdRestorePost>>, TError,{taskId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof restoreTaskApiV1TasksTaskIdRestorePost>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['restoreTaskApiV1TasksTaskIdRestorePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreTaskApiV1TasksTaskIdRestorePost>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  restoreTaskApiV1TasksTaskIdRestorePost(taskId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RestoreTaskApiV1TasksTaskIdRestorePostMutationResult = NonNullable<Awaited<ReturnType<typeof restoreTaskApiV1TasksTaskIdRestorePost>>>
    
    export type RestoreTaskApiV1TasksTaskIdRestorePostMutationError = HTTPValidationError

    /**
 * @summary Restore Task
 */
export const useRestoreTaskApiV1TasksTaskIdRestorePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreTaskApiV1TasksTaskIdRestorePost>>, TError,{taskId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreTaskApiV1TasksTaskIdRestorePost>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getRestoreTaskApiV1TasksTaskIdRestorePostMutationOptions(options), queryClient);
    }
    /**
 * Complete a non-recurring task.
 * @summary Complete Task
 */
export const completeTaskApiV1TasksTaskIdCompletePost = (
    taskId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/tasks/${taskId}/complete`, method: 'POST', signal
    },
      );
    }
  


export const getCompleteTaskApiV1TasksTaskIdCompletePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeTaskApiV1TasksTaskIdCompletePost>>, TError,{taskId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof completeTaskApiV1TasksTaskIdCompletePost>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['completeTaskApiV1TasksTaskIdCompletePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeTaskApiV1TasksTaskIdCompletePost>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  completeTaskApiV1TasksTaskIdCompletePost(taskId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteTaskApiV1TasksTaskIdCompletePostMutationResult = NonNullable<Awaited<ReturnType<typeof completeTaskApiV1TasksTaskIdCompletePost>>>
    
    export type CompleteTaskApiV1TasksTaskIdCompletePostMutationError = HTTPValidationError

    /**
 * @summary Complete Task
 */
export const useCompleteTaskApiV1TasksTaskIdCompletePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeTaskApiV1TasksTaskIdCompletePost>>, TError,{taskId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeTaskApiV1TasksTaskIdCompletePost>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getCompleteTaskApiV1TasksTaskIdCompletePostMutationOptions(options), queryClient);
    }
    /**
 * Uncomplete a task (mark as pending).
 * @summary Uncomplete Task
 */
export const uncompleteTaskApiV1TasksTaskIdUncompletePost = (
    taskId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/tasks/${taskId}/uncomplete`, method: 'POST', signal
    },
      );
    }
  


export const getUncompleteTaskApiV1TasksTaskIdUncompletePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uncompleteTaskApiV1TasksTaskIdUncompletePost>>, TError,{taskId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uncompleteTaskApiV1TasksTaskIdUncompletePost>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['uncompleteTaskApiV1TasksTaskIdUncompletePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uncompleteTaskApiV1TasksTaskIdUncompletePost>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  uncompleteTaskApiV1TasksTaskIdUncompletePost(taskId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UncompleteTaskApiV1TasksTaskIdUncompletePostMutationResult = NonNullable<Awaited<ReturnType<typeof uncompleteTaskApiV1TasksTaskIdUncompletePost>>>
    
    export type UncompleteTaskApiV1TasksTaskIdUncompletePostMutationError = HTTPValidationError

    /**
 * @summary Uncomplete Task
 */
export const useUncompleteTaskApiV1TasksTaskIdUncompletePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uncompleteTaskApiV1TasksTaskIdUncompletePost>>, TError,{taskId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uncompleteTaskApiV1TasksTaskIdUncompletePost>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getUncompleteTaskApiV1TasksTaskIdUncompletePostMutationOptions(options), queryClient);
    }
    /**
 * Toggle a task's completion status.

For recurring tasks, this toggles the instance for the specified date
(or today if no date provided).
 * @summary Toggle Task Complete
 */
export const toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost = (
    taskId: number,
    toggleCompleteRequestNull: ToggleCompleteRequest | null,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/tasks/${taskId}/toggle-complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: toggleCompleteRequestNull, signal
    },
      );
    }
  


export const getToggleTaskCompleteApiV1TasksTaskIdToggleCompletePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost>>, TError,{taskId: number;data: ToggleCompleteRequest | null}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost>>, TError,{taskId: number;data: ToggleCompleteRequest | null}, TContext> => {

const mutationKey = ['toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost>>, {taskId: number;data: ToggleCompleteRequest | null}> = (props) => {
          const {taskId,data} = props ?? {};

          return  toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost(taskId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleTaskCompleteApiV1TasksTaskIdToggleCompletePostMutationResult = NonNullable<Awaited<ReturnType<typeof toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost>>>
    export type ToggleTaskCompleteApiV1TasksTaskIdToggleCompletePostMutationBody = ToggleCompleteRequest | null
    export type ToggleTaskCompleteApiV1TasksTaskIdToggleCompletePostMutationError = HTTPValidationError

    /**
 * @summary Toggle Task Complete
 */
export const useToggleTaskCompleteApiV1TasksTaskIdToggleCompletePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost>>, TError,{taskId: number;data: ToggleCompleteRequest | null}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleTaskCompleteApiV1TasksTaskIdToggleCompletePost>>,
        TError,
        {taskId: number;data: ToggleCompleteRequest | null},
        TContext
      > => {
      return useMutation(getToggleTaskCompleteApiV1TasksTaskIdToggleCompletePostMutationOptions(options), queryClient);
    }
    /**
 * Batch update task content (title and description).

Used when enabling encryption (to save encrypted content) or
disabling encryption (to save decrypted content).

**Non-Atomic Behavior:** Commits in batches of 25 to prevent connection
timeouts on cloud databases (Railway, etc). If an error occurs mid-batch,
previously committed batches remain persisted. The operation is idempotent -
retry to complete any remaining tasks.

Returns:
    - updated_count: Number of tasks successfully updated
    - total_requested: Total tasks in request
    - errors: List of {id, error} for failed tasks (only if any failed)
 * @summary Batch Update Tasks
 */
export const batchUpdateTasksApiV1TasksBatchUpdatePost = (
    batchUpdateTasksRequest: BatchUpdateTasksRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/tasks/batch-update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: batchUpdateTasksRequest, signal
    },
      );
    }
  


export const getBatchUpdateTasksApiV1TasksBatchUpdatePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchUpdateTasksApiV1TasksBatchUpdatePost>>, TError,{data: BatchUpdateTasksRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof batchUpdateTasksApiV1TasksBatchUpdatePost>>, TError,{data: BatchUpdateTasksRequest}, TContext> => {

const mutationKey = ['batchUpdateTasksApiV1TasksBatchUpdatePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof batchUpdateTasksApiV1TasksBatchUpdatePost>>, {data: BatchUpdateTasksRequest}> = (props) => {
          const {data} = props ?? {};

          return  batchUpdateTasksApiV1TasksBatchUpdatePost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type BatchUpdateTasksApiV1TasksBatchUpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof batchUpdateTasksApiV1TasksBatchUpdatePost>>>
    export type BatchUpdateTasksApiV1TasksBatchUpdatePostMutationBody = BatchUpdateTasksRequest
    export type BatchUpdateTasksApiV1TasksBatchUpdatePostMutationError = HTTPValidationError

    /**
 * @summary Batch Update Tasks
 */
export const useBatchUpdateTasksApiV1TasksBatchUpdatePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchUpdateTasksApiV1TasksBatchUpdatePost>>, TError,{data: BatchUpdateTasksRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof batchUpdateTasksApiV1TasksBatchUpdatePost>>,
        TError,
        {data: BatchUpdateTasksRequest},
        TContext
      > => {
      return useMutation(getBatchUpdateTasksApiV1TasksBatchUpdatePostMutationOptions(options), queryClient);
    }
    