/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DemoLoginAuthDemoGetParams,
  DisconnectTodoistAuthTodoistDisconnectPost200,
  GoogleCallbackAuthGoogleCallbackGetParams,
  GoogleLoginAuthGoogleGetParams,
  HTTPValidationError,
  TodoistCallbackAuthTodoistCallbackGetParams,
  TodoistLoginAuthTodoistGetParams
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Redirect to Todoist OAuth.
 * @summary Todoist Login
 */
export const todoistLoginAuthTodoistGet = (
    params?: TodoistLoginAuthTodoistGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/auth/todoist`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getTodoistLoginAuthTodoistGetQueryKey = (params?: TodoistLoginAuthTodoistGetParams,) => {
    return [
    `/auth/todoist`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getTodoistLoginAuthTodoistGetQueryOptions = <TData = Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError = HTTPValidationError>(params?: TodoistLoginAuthTodoistGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTodoistLoginAuthTodoistGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>> = ({ signal }) => todoistLoginAuthTodoistGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TodoistLoginAuthTodoistGetQueryResult = NonNullable<Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>>
export type TodoistLoginAuthTodoistGetQueryError = HTTPValidationError


export function useTodoistLoginAuthTodoistGet<TData = Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError = HTTPValidationError>(
 params: undefined |  TodoistLoginAuthTodoistGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>,
          TError,
          Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTodoistLoginAuthTodoistGet<TData = Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError = HTTPValidationError>(
 params?: TodoistLoginAuthTodoistGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>,
          TError,
          Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTodoistLoginAuthTodoistGet<TData = Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError = HTTPValidationError>(
 params?: TodoistLoginAuthTodoistGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Todoist Login
 */

export function useTodoistLoginAuthTodoistGet<TData = Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError = HTTPValidationError>(
 params?: TodoistLoginAuthTodoistGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistLoginAuthTodoistGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTodoistLoginAuthTodoistGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Handle Todoist OAuth callback.
 * @summary Todoist Callback
 */
export const todoistCallbackAuthTodoistCallbackGet = (
    params?: TodoistCallbackAuthTodoistCallbackGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/auth/todoist/callback`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getTodoistCallbackAuthTodoistCallbackGetQueryKey = (params?: TodoistCallbackAuthTodoistCallbackGetParams,) => {
    return [
    `/auth/todoist/callback`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getTodoistCallbackAuthTodoistCallbackGetQueryOptions = <TData = Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError = HTTPValidationError>(params?: TodoistCallbackAuthTodoistCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTodoistCallbackAuthTodoistCallbackGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>> = ({ signal }) => todoistCallbackAuthTodoistCallbackGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TodoistCallbackAuthTodoistCallbackGetQueryResult = NonNullable<Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>>
export type TodoistCallbackAuthTodoistCallbackGetQueryError = HTTPValidationError


export function useTodoistCallbackAuthTodoistCallbackGet<TData = Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError = HTTPValidationError>(
 params: undefined |  TodoistCallbackAuthTodoistCallbackGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>,
          TError,
          Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTodoistCallbackAuthTodoistCallbackGet<TData = Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError = HTTPValidationError>(
 params?: TodoistCallbackAuthTodoistCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>,
          TError,
          Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTodoistCallbackAuthTodoistCallbackGet<TData = Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError = HTTPValidationError>(
 params?: TodoistCallbackAuthTodoistCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Todoist Callback
 */

export function useTodoistCallbackAuthTodoistCallbackGet<TData = Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError = HTTPValidationError>(
 params?: TodoistCallbackAuthTodoistCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof todoistCallbackAuthTodoistCallbackGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTodoistCallbackAuthTodoistCallbackGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Redirect to Google OAuth. Set write_scope=true to request calendar write access.
 * @summary Google Login
 */
export const googleLoginAuthGoogleGet = (
    params?: GoogleLoginAuthGoogleGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/auth/google`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGoogleLoginAuthGoogleGetQueryKey = (params?: GoogleLoginAuthGoogleGetParams,) => {
    return [
    `/auth/google`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGoogleLoginAuthGoogleGetQueryOptions = <TData = Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError = HTTPValidationError>(params?: GoogleLoginAuthGoogleGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGoogleLoginAuthGoogleGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>> = ({ signal }) => googleLoginAuthGoogleGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GoogleLoginAuthGoogleGetQueryResult = NonNullable<Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>>
export type GoogleLoginAuthGoogleGetQueryError = HTTPValidationError


export function useGoogleLoginAuthGoogleGet<TData = Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError = HTTPValidationError>(
 params: undefined |  GoogleLoginAuthGoogleGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>,
          TError,
          Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleLoginAuthGoogleGet<TData = Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError = HTTPValidationError>(
 params?: GoogleLoginAuthGoogleGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>,
          TError,
          Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleLoginAuthGoogleGet<TData = Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError = HTTPValidationError>(
 params?: GoogleLoginAuthGoogleGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Google Login
 */

export function useGoogleLoginAuthGoogleGet<TData = Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError = HTTPValidationError>(
 params?: GoogleLoginAuthGoogleGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLoginAuthGoogleGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGoogleLoginAuthGoogleGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Handle Google OAuth callback.
 * @summary Google Callback
 */
export const googleCallbackAuthGoogleCallbackGet = (
    params: GoogleCallbackAuthGoogleCallbackGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/auth/google/callback`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGoogleCallbackAuthGoogleCallbackGetQueryKey = (params?: GoogleCallbackAuthGoogleCallbackGetParams,) => {
    return [
    `/auth/google/callback`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGoogleCallbackAuthGoogleCallbackGetQueryOptions = <TData = Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError = HTTPValidationError>(params: GoogleCallbackAuthGoogleCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGoogleCallbackAuthGoogleCallbackGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>> = ({ signal }) => googleCallbackAuthGoogleCallbackGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GoogleCallbackAuthGoogleCallbackGetQueryResult = NonNullable<Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>>
export type GoogleCallbackAuthGoogleCallbackGetQueryError = HTTPValidationError


export function useGoogleCallbackAuthGoogleCallbackGet<TData = Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError = HTTPValidationError>(
 params: GoogleCallbackAuthGoogleCallbackGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>,
          TError,
          Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleCallbackAuthGoogleCallbackGet<TData = Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError = HTTPValidationError>(
 params: GoogleCallbackAuthGoogleCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>,
          TError,
          Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleCallbackAuthGoogleCallbackGet<TData = Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError = HTTPValidationError>(
 params: GoogleCallbackAuthGoogleCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Google Callback
 */

export function useGoogleCallbackAuthGoogleCallbackGet<TData = Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError = HTTPValidationError>(
 params: GoogleCallbackAuthGoogleCallbackGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallbackAuthGoogleCallbackGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGoogleCallbackAuthGoogleCallbackGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Clear session and redirect to home.
 * @summary Logout
 */
export const logoutAuthLogoutGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/auth/logout`, method: 'GET', signal
    },
      );
    }
  



export const getLogoutAuthLogoutGetQueryKey = () => {
    return [
    `/auth/logout`
    ] as const;
    }

    
export const getLogoutAuthLogoutGetQueryOptions = <TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogoutAuthLogoutGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logoutAuthLogoutGet>>> = ({ signal }) => logoutAuthLogoutGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LogoutAuthLogoutGetQueryResult = NonNullable<Awaited<ReturnType<typeof logoutAuthLogoutGet>>>
export type LogoutAuthLogoutGetQueryError = unknown


export function useLogoutAuthLogoutGet<TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutAuthLogoutGet>>,
          TError,
          Awaited<ReturnType<typeof logoutAuthLogoutGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogoutAuthLogoutGet<TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutAuthLogoutGet>>,
          TError,
          Awaited<ReturnType<typeof logoutAuthLogoutGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogoutAuthLogoutGet<TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Logout
 */

export function useLogoutAuthLogoutGet<TData = Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutAuthLogoutGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLogoutAuthLogoutGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Disconnect Todoist by removing the stored token.
 * @summary Disconnect Todoist
 */
export const disconnectTodoistAuthTodoistDisconnectPost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<DisconnectTodoistAuthTodoistDisconnectPost200>(
      {url: `/auth/todoist/disconnect`, method: 'POST', signal
    },
      );
    }
  


export const getDisconnectTodoistAuthTodoistDisconnectPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnectTodoistAuthTodoistDisconnectPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof disconnectTodoistAuthTodoistDisconnectPost>>, TError,void, TContext> => {

const mutationKey = ['disconnectTodoistAuthTodoistDisconnectPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disconnectTodoistAuthTodoistDisconnectPost>>, void> = () => {
          

          return  disconnectTodoistAuthTodoistDisconnectPost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DisconnectTodoistAuthTodoistDisconnectPostMutationResult = NonNullable<Awaited<ReturnType<typeof disconnectTodoistAuthTodoistDisconnectPost>>>
    
    export type DisconnectTodoistAuthTodoistDisconnectPostMutationError = unknown

    /**
 * @summary Disconnect Todoist
 */
export const useDisconnectTodoistAuthTodoistDisconnectPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disconnectTodoistAuthTodoistDisconnectPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disconnectTodoistAuthTodoistDisconnectPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDisconnectTodoistAuthTodoistDisconnectPostMutationOptions(options), queryClient);
    }
    /**
 * Demo login - bypasses Google OAuth for testing/previews.
 * @summary Demo Login
 */
export const demoLoginAuthDemoGet = (
    params?: DemoLoginAuthDemoGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/auth/demo`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getDemoLoginAuthDemoGetQueryKey = (params?: DemoLoginAuthDemoGetParams,) => {
    return [
    `/auth/demo`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getDemoLoginAuthDemoGetQueryOptions = <TData = Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError = HTTPValidationError>(params?: DemoLoginAuthDemoGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDemoLoginAuthDemoGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof demoLoginAuthDemoGet>>> = ({ signal }) => demoLoginAuthDemoGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DemoLoginAuthDemoGetQueryResult = NonNullable<Awaited<ReturnType<typeof demoLoginAuthDemoGet>>>
export type DemoLoginAuthDemoGetQueryError = HTTPValidationError


export function useDemoLoginAuthDemoGet<TData = Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError = HTTPValidationError>(
 params: undefined |  DemoLoginAuthDemoGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof demoLoginAuthDemoGet>>,
          TError,
          Awaited<ReturnType<typeof demoLoginAuthDemoGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDemoLoginAuthDemoGet<TData = Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError = HTTPValidationError>(
 params?: DemoLoginAuthDemoGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof demoLoginAuthDemoGet>>,
          TError,
          Awaited<ReturnType<typeof demoLoginAuthDemoGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDemoLoginAuthDemoGet<TData = Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError = HTTPValidationError>(
 params?: DemoLoginAuthDemoGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Demo Login
 */

export function useDemoLoginAuthDemoGet<TData = Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError = HTTPValidationError>(
 params?: DemoLoginAuthDemoGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof demoLoginAuthDemoGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDemoLoginAuthDemoGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Reset demo user data back to initial seed state.
 * @summary Demo Reset
 */
export const demoResetAuthDemoResetPost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/auth/demo/reset`, method: 'POST', signal
    },
      );
    }
  


export const getDemoResetAuthDemoResetPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof demoResetAuthDemoResetPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof demoResetAuthDemoResetPost>>, TError,void, TContext> => {

const mutationKey = ['demoResetAuthDemoResetPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof demoResetAuthDemoResetPost>>, void> = () => {
          

          return  demoResetAuthDemoResetPost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DemoResetAuthDemoResetPostMutationResult = NonNullable<Awaited<ReturnType<typeof demoResetAuthDemoResetPost>>>
    
    export type DemoResetAuthDemoResetPostMutationError = unknown

    /**
 * @summary Demo Reset
 */
export const useDemoResetAuthDemoResetPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof demoResetAuthDemoResetPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof demoResetAuthDemoResetPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDemoResetAuthDemoResetPostMutationOptions(options), queryClient);
    }
    