/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.56.17
 */

/**
 * A single activity log entry.
 */
export interface ActivityLogEntry {
  id: number;
  user_id: number;
  task_id: number | null;
  instance_id: number | null;
  domain_id: number | null;
  event_type: string;
  field_name: string | null;
  old_value: string | null;
  new_value: string | null;
  batch_id: string | null;
  created_at: string;
}
