/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

export interface AgingBuckets {
  same_day: number;
  within_week: number;
  within_month: number;
  over_month: number;
}
