/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */
import type { AgingBuckets } from './agingBuckets';

export interface AgingStatsResponse {
  buckets: AgingBuckets;
  avg_days: number;
  median_days: number;
  total_completed: number;
}
