/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */
import type { AppRoutersTasksDomainContentData } from './appRoutersTasksDomainContentData';
import type { TaskContentData } from './taskContentData';

/**
 * Response containing all tasks and domains for encryption operations.
 */
export interface AllDataResponse {
  tasks: TaskContentData[];
  domains: AppRoutersTasksDomainContentData[];
}
