/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */
import type { AppRoutersDomainsDomainContentData } from './appRoutersDomainsDomainContentData';
import type { TaskContentData } from './taskContentData';

/**
 * Response containing all tasks and domains for encryption operations.
 */
export interface AllDataResponse {
  tasks: TaskContentData[];
  domains: AppRoutersDomainsDomainContentData[];
}
