/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */
import type { AgingStatsResponse } from './agingStatsResponse';
import type { DailyCompletionItem } from './dailyCompletionItem';
import type { DayOfWeekItem } from './dayOfWeekItem';
import type { DomainBreakdownItem } from './domainBreakdownItem';
import type { HeatmapItem } from './heatmapItem';
import type { HourOfDayItem } from './hourOfDayItem';
import type { ImpactDistributionItem } from './impactDistributionItem';
import type { RecurringStatItem } from './recurringStatItem';
import type { StreaksResponse } from './streaksResponse';
import type { VelocityItem } from './velocityItem';
import type { WeekComparisonResponse } from './weekComparisonResponse';

export interface AnalyticsResponse {
  total_completed: number;
  total_pending: number;
  completion_rate: number;
  daily_completions: DailyCompletionItem[];
  by_domain: DomainBreakdownItem[];
  by_day_of_week: DayOfWeekItem[];
  by_hour: HourOfDayItem[];
  impact_distribution: ImpactDistributionItem[];
  heatmap_data: HeatmapItem[];
  velocity_data: VelocityItem[];
  streaks: StreaksResponse;
  week_comparison: WeekComparisonResponse;
  recurring_stats: RecurringStatItem[];
  aging_stats: AgingStatsResponse;
}
