/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

/**
 * Response from import operation.
 */
export interface AppRoutersImportDataImportResponse {
  success: boolean;
  domains_created: number;
  domains_skipped: number;
  tasks_created: number;
  tasks_skipped: number;
  tasks_completed: number;
  parent_tasks_imported: number;
  tasks_need_clarity: number;
  errors: string[];
}
