/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

/**
 * Response from import operation.
 */
export interface AppRoutersBackupImportResponse {
  success: boolean;
  domains: number;
  tasks: number;
  preferences: number;
}
