/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */
import type { TaskMetadataResponse } from './taskMetadataResponse';

/**
 * Complete task representation with parsed metadata.
 */
export interface AppRoutersApiTaskResponse {
  id: string;
  content: string;
  description: string;
  project_id: string;
  project_name: string;
  labels: string[];
  metadata: TaskMetadataResponse;
  due_date: string | null;
  due_datetime: string | null;
  is_recurring: boolean;
  duration_minutes: number | null;
  priority: number;
  parent_id: string | null;
  subtask_count: number;
}
