/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

/**
 * Single domain's content for batch update.
 */
export interface AppRoutersTasksDomainContentData {
  id: number;
  name: string;
}
