/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.82
 */

export type AuthenticationOptionsResponseOptions = { [key: string]: unknown };
