/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */
import type { AuthenticationOptionsResponseOptions } from './authenticationOptionsResponseOptions';

/**
 * WebAuthn authentication options for the browser.
 */
export interface AuthenticationOptionsResponse {
  options: AuthenticationOptionsResponseOptions;
  prf_salt?: string | null;
  wrapped_key?: string | null;
  has_passkeys: boolean;
}
