/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

/**
 * Response after successful passkey authentication.
 */
export interface AuthenticationVerifyResponse {
  success: boolean;
  prf_salt: string;
  wrapped_key: string;
}
