/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */
import type { AuthenticationVerifyRequestCredential } from './authenticationVerifyRequestCredential';

/**
 * Request to verify passkey authentication.
 */
export interface AuthenticationVerifyRequest {
  credential: AuthenticationVerifyRequestCredential;
}
