/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */
import type { AppRoutersDomainsDomainContentData } from './appRoutersDomainsDomainContentData';

/**
 * Request body for batch updating domain names.
 */
export interface BatchUpdateDomainsRequest {
  /** @maxItems 500 */
  domains: AppRoutersDomainsDomainContentData[];
}
