/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */
import type { AppRoutersTasksDomainContentData } from './appRoutersTasksDomainContentData';

/**
 * Request body for batch updating domain names.
 */
export interface BatchUpdateDomainsRequest {
  /** @maxItems 500 */
  domains: AppRoutersTasksDomainContentData[];
}
