/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

/**
 * Response for batch-complete instances.
 */
export interface BatchCompleteResponse {
  completed_count: number;
}
