/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */
import type { BatchUpdateError } from './batchUpdateError';

/**
 * Response for batch-update tasks.
 */
export interface BatchUpdateTasksResponse {
  updated_count: number;
  total_requested: number;
  failed_ids?: number[] | null;
  errors?: BatchUpdateError[] | null;
}
