/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.82
 */
import type { TaskContentData } from './taskContentData';

/**
 * Request body for batch updating task content.
 */
export interface BatchUpdateTasksRequest {
  /** @maxItems 5000 */
  tasks: TaskContentData[];
}
