/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */
import type { BatchActionRequestAction } from './batchActionRequestAction';

/**
 * Request body for batch task actions.
 */
export interface BatchActionRequest {
  /** @maxItems 100 */
  task_ids: number[];
  action: BatchActionRequestAction;
  scheduled_date?: string | null;
  domain_id?: number | null;
}
