/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.68
 */

export type BatchActionAction = typeof BatchActionAction[keyof typeof BatchActionAction];


export const BatchActionAction = {
  complete: 'complete',
  skip: 'skip',
} as const;
