/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */
import type { BatchActionAction } from './batchActionAction';

/**
 * Request body for batch actions on all past instances.
 */
export interface BatchAction {
  action: BatchActionAction;
}
