/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

/**
 * Request body for batch completing instances of a single task.
 */
export interface BatchCompleteRequest {
  task_id: number;
  before_date: string;
}
