/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

/**
 * A single error in a batch update.
 */
export interface BatchUpdateError {
  id: number;
  error: string;
}
