/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

export interface BulkSyncResponse {
  success: boolean;
  created?: number;
  updated?: number;
  deleted?: number;
  skipped?: number;
  error?: string | null;
}
