/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */

/**
 * Request body for bulk calendar selections.
 */
export interface CalendarSelectionsRequest {
  /** @maxItems 100 */
  calendar_ids: string[];
}
