/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

/**
 * Result of committing a single task.
 */
export interface CommitTaskResult {
  task_id: string;
  success: boolean;
  error?: string | null;
}
