/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */
import type { CommitTaskResult } from './commitTaskResult';

/**
 * Response from task commit operation.
 */
export interface CommitTasksResponse {
  results: CommitTaskResult[];
  success_count: number;
  failure_count: number;
}
