/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */
import type { ScheduledTaskUpdate } from './scheduledTaskUpdate';

/**
 * Request to commit scheduled tasks to Todoist.
 */
export interface CommitTasksRequest {
  /** @maxItems 500 */
  tasks: ScheduledTaskUpdate[];
}
