/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

/**
 * Response after deleting a passkey.
 */
export interface DeletePasskeyResponse {
  success: boolean;
  message: string;
}
