/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */

/**
 * Response model for a domain.
 */
export interface DomainResponse {
  id: number;
  name: string;
  color: string | null;
  icon: string | null;
  position: number;
  is_archived: boolean;
}
