/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */

/**
 * Request body for creating a domain.
 */
export interface DomainCreate {
  name: string;
  color?: string | null;
  icon?: string | null;
}
