/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

/**
 * Request body for updating a domain.
 */
export interface DomainUpdate {
  name?: string | null;
  color?: string | null;
  icon?: string | null;
  position?: number | null;
}
