/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

export interface DomainBreakdownItem {
  domain_id: number;
  domain_name: string;
  domain_icon: string;
  count: number;
}
