/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */

/**
 * Response after setting up encryption.
 */
export interface EncryptionSetupResponse {
  success: boolean;
  message: string;
}
