/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

/**
 * Request to set up E2E encryption.
 */
export interface EncryptionSetupRequest {
  /** @maxLength 64 */
  salt: string;
  /** @maxLength 1000 */
  test_value: string;
}
