/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

/**
 * Response model for encryption status.
 */
export interface EncryptionStatusResponse {
  enabled: boolean;
  salt?: string | null;
  test_value?: string | null;
}
