/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

/**
 * Google Calendar event.
 */
export interface EventResponse {
  id: string;
  summary: string;
  description: string | null;
  start: string;
  end: string;
  all_day: boolean;
  calendar_id: string;
  html_link: string | null;
}
