/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

/**
 * Google Calendar event.
 */
export interface EventResponse {
  id: string;
  summary: string;
  description: string | null;
  start: string;
  end: string;
  all_day: boolean;
  calendar_id: string;
}
