/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.82
 */

export interface FeedStatusResponse {
  enabled: boolean;
  feed_url?: string | null;
  gcal_sync_enabled?: boolean;
  encryption_enabled?: boolean;
}
