/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */

export type GetAnalyticsApiV1AnalyticsGetParams = {
/**
 * @minimum 7
 * @maximum 90
 */
days?: number;
};
