/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

export type GetEventsApiV1EventsGetParams = {
start_date?: string;
end_date?: string;
};
