/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.82
 */

export type GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams = {
/**
 * @minimum 1
 * @maximum 50
 */
limit?: number;
};
