/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

export type GoogleCallbackAuthGoogleCallbackGetParams = {
code: string;
state: string;
};
