/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

export type GoogleLoginAuthGoogleGetParams = {
wizard?: boolean;
write_scope?: boolean;
};
