/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */

export type GoogleLoginAuthGoogleGetParams = {
wizard?: boolean;
write_scope?: boolean;
};
