/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

export interface ImpactDistributionItem {
  impact: number;
  label: string;
  count: number;
  color: string;
}
