/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

/**
 * Options for Todoist import.
 */
export interface ImportOptions {
  include_completed?: boolean;
  /**
   * @minimum 0
   * @maximum 1000
   */
  completed_limit?: number;
  skip_existing?: boolean;
}
