/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */
import type { ImportPreviewResponseProjectsItem } from './importPreviewResponseProjectsItem';

/**
 * Preview of what will be imported from Todoist.
 */
export interface ImportPreviewResponse {
  projects_count: number;
  tasks_count: number;
  subtasks_count: number;
  completed_count: number;
  projects: ImportPreviewResponseProjectsItem[];
}
