/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

/**
 * Request body for rescheduling an instance.
 */
export interface InstanceSchedule {
  scheduled_datetime: string | null;
}
