/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

/**
 * Request body for rescheduling an instance.
 */
export interface InstanceSchedule {
  scheduled_datetime: string;
}
