/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.56.17
 */

/**
 * Response for instance complete/uncomplete/skip.
 */
export interface InstanceStatusResponse {
  status: string;
  instance_id: number;
}
