/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

/**
 * Response for instance toggle-complete.
 */
export interface InstanceToggleCompleteResponse {
  status: string;
  instance_id: number;
  completed: boolean;
}
