/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

/**
 * Response model for a task instance.
 */
export interface InstanceResponse {
  id: number;
  task_id: number;
  task_title: string;
  instance_date: string;
  scheduled_datetime: string | null;
  status: string;
  duration_minutes: number | null;
  impact: number;
  clarity: string | null;
  domain_name?: string | null;
}
