/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

export type ListTasksApiV1TasksGetParams = {
/**
 * Filter by domain ID
 */
domain_id?: number | null;
/**
 * Filter by status
 */
status?: string;
/**
 * Filter by scheduled date
 */
scheduled_date?: string | null;
/**
 * Filter recurring/non-recurring
 */
is_recurring?: boolean | null;
/**
 * Filter by clarity (executable/defined/exploratory/none)
 */
clarity?: string | null;
/**
 * Get subtasks of a task
 */
parent_id?: number | null;
};
