/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

export type ListInstancesApiV1InstancesGetParams = {
/**
 * Start of date range
 */
start_date: string;
/**
 * End of date range
 */
end_date: string;
/**
 * Filter by status
 */
status?: string | null;
};
