/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.68
 */

export type ListTasksApiV1TasksGetParams = {
/**
 * Filter by domain ID
 */
domain_id?: number | null;
/**
 * Filter by status
 */
status?: string;
/**
 * Filter by scheduled date
 */
scheduled_date?: string | null;
/**
 * Filter recurring/non-recurring
 */
is_recurring?: boolean | null;
/**
 * Filter by clarity (executable/defined/exploratory/none)
 */
clarity?: string | null;
/**
 * Get subtasks of a task
 */
parent_id?: number | null;
/**
 * Max tasks to return
 */
limit?: number | null;
/**
 * Number of tasks to skip
 */
offset?: number | null;
};
