/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */

export interface MeResponse {
  name: string | null;
  email: string;
  is_demo_user: boolean;
  encryption_enabled: boolean;
  calendar_connected: boolean;
}
