/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */
import type { PasskeyInfo } from './passkeyInfo';

/**
 * Response with list of user's passkeys.
 */
export interface PasskeyListResponse {
  passkeys: PasskeyInfo[];
  count: number;
}
