/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

/**
 * Response for pending-past-count.
 */
export interface PendingPastCountResponse {
  pending_count: number;
}
