/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.68
 */

/**
 * Response for pending-past-count.
 */
export interface PendingPastCountResponse {
  pending_count: number;
}
