/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

/**
 * Response model for user preferences.
 */
export interface PreferencesResponse {
  show_completed_in_planner: boolean;
  completed_retention_days: number;
  completed_move_to_bottom: boolean;
  completed_sort_by_date: boolean;
  show_completed_in_list: boolean;
  hide_recurring_after_completion: boolean;
  show_scheduled_in_list: boolean;
  scheduled_move_to_bottom: boolean;
  scheduled_sort_by_date: boolean;
  timezone?: string | null;
  calendar_hour_height?: number;
  gcal_sync_enabled?: boolean;
}
