/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

/**
 * Request body for updating preferences.
 */
export interface PreferencesUpdate {
  show_completed_in_planner?: boolean | null;
  completed_retention_days?: number | null;
  show_completed_in_list?: boolean | null;
  hide_recurring_after_completion?: boolean | null;
  show_scheduled_in_list?: boolean | null;
  timezone?: string | null;
  calendar_hour_height?: number | null;
}
