/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */

export interface RecentCompletionItem {
  id: number;
  task_id: number;
  title: string;
  completed_at_display: string;
  domain_name: string;
  domain_icon: string;
  is_instance: boolean;
}
