/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

export interface RecurringStatItem {
  task_id: number;
  title: string;
  completed: number;
  total: number;
  rate: number;
}
