/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */
import type { RecurrenceRuleSchemaFreq } from './recurrenceRuleSchemaFreq';

/**
 * Validated shape for recurrence_rule JSON.
 */
export interface RecurrenceRuleSchema {
  freq: RecurrenceRuleSchemaFreq;
  /**
   * @minimum 1
   * @maximum 99
   */
  interval?: number;
  days_of_week?: string[] | null;
  day_of_month?: number | null;
  week_of_month?: number | null;
  month_of_year?: number | null;
}
