/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */
import type { RegistrationVerifyRequestCredential } from './registrationVerifyRequestCredential';

/**
 * Request to verify and store a new passkey.
 */
export interface RegistrationVerifyRequest {
  credential: RegistrationVerifyRequestCredential;
  /** @maxLength 100 */
  name: string;
  /** @maxLength 64 */
  prf_salt: string;
  /** @maxLength 10000 */
  wrapped_key: string;
}
