/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */
import type { RegistrationOptionsResponseOptions } from './registrationOptionsResponseOptions';

/**
 * WebAuthn registration options for the browser.
 */
export interface RegistrationOptionsResponse {
  options: RegistrationOptionsResponseOptions;
  challenge: string;
}
