/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

/**
 * Response after successful passkey registration.
 */
export interface RegistrationVerifyResponse {
  success: boolean;
  passkey_id: number;
  name: string;
}
