/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

/**
 * Task scheduling update payload.
 */
export interface ScheduledTaskUpdate {
  task_id: string;
  due_datetime: string;
  /**
   * @minimum 1
   * @maximum 1440
   */
  duration_minutes: number;
}
