/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

/**
 * Single snapshot metadata.
 */
export interface SnapshotInfo {
  id: number;
  size_bytes: number;
  is_manual: boolean;
  created_at: string;
}
