/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */
import type { SnapshotInfo } from './snapshotInfo';

/**
 * List of snapshots plus enabled state.
 */
export interface SnapshotListResponse {
  snapshots: SnapshotInfo[];
  enabled: boolean;
}
