/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */

export interface StreaksResponse {
  current: number;
  longest: number;
  this_week: number;
}
