/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

/**
 * Response model for a subtask (without nested subtasks).
 */
export interface SubtaskResponse {
  id: number;
  title: string;
  description: string | null;
  duration_minutes: number | null;
  impact: number;
  clarity: string | null;
  scheduled_date: string | null;
  status: string;
  position: number;
}
