/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

export interface SyncEnableResponse {
  success: boolean;
  message: string;
  calendar_id?: string | null;
  needs_reauth?: boolean;
  reauth_url?: string | null;
}
