/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

export interface SyncStatusResponse {
  enabled: boolean;
  calendar_id?: string | null;
  synced_count?: number;
  has_write_scope?: boolean;
  reauth_url?: string | null;
  sync_error?: string | null;
  syncing?: boolean;
}
