/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

export interface SyncDisableResponse {
  success: boolean;
  message: string;
  deleted_count?: number;
}
