/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */

/**
 * Response for task complete/uncomplete.
 */
export interface TaskCompleteResponse {
  status: string;
  task_id: number;
}
