/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */

/**
 * Parsed task metadata from labels and description.
 */
export interface TaskMetadataResponse {
  clarity: string | null;
  clarity_display: string;
  other_labels: string[];
}
