/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */
import type { RecurrenceRuleSchema } from './recurrenceRuleSchema';

/**
 * Request body for creating a task.
 */
export interface TaskCreate {
  title: string;
  description?: string | null;
  domain_id?: number | null;
  parent_id?: number | null;
  duration_minutes?: number | null;
  /**
   * @minimum 1
   * @maximum 4
   */
  impact?: number;
  clarity?: string;
  scheduled_date?: string | null;
  scheduled_time?: string | null;
  is_recurring?: boolean;
  recurrence_rule?: RecurrenceRuleSchema | null;
  recurrence_start?: string | null;
  recurrence_end?: string | null;
  reminder_minutes_before?: number | null;
}
