/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */
import type { TaskCreateRecurrenceRule } from './taskCreateRecurrenceRule';

/**
 * Request body for creating a task.
 */
export interface TaskCreate {
  title: string;
  description?: string | null;
  domain_id?: number | null;
  parent_id?: number | null;
  duration_minutes?: number | null;
  /**
   * @minimum 1
   * @maximum 4
   */
  impact?: number;
  clarity?: string;
  scheduled_date?: string | null;
  scheduled_time?: string | null;
  is_recurring?: boolean;
  recurrence_rule?: TaskCreateRecurrenceRule;
  recurrence_start?: string | null;
  recurrence_end?: string | null;
}
