/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */
import type { SubtaskResponse } from './subtaskResponse';
import type { TaskResponseRecurrenceRule } from './taskResponseRecurrenceRule';

/**
 * Response model for a task.
 */
export interface TaskResponse {
  id: number;
  title: string;
  description: string | null;
  domain_id: number | null;
  domain_name?: string | null;
  parent_id: number | null;
  duration_minutes: number | null;
  impact: number;
  clarity: string | null;
  scheduled_date: string | null;
  scheduled_time: string | null;
  is_recurring: boolean;
  recurrence_rule: TaskResponseRecurrenceRule;
  recurrence_start?: string | null;
  recurrence_end?: string | null;
  status: string;
  position: number;
  created_at?: string | null;
  completed_at?: string | null;
  subtasks?: SubtaskResponse[];
  today_instance_completed?: boolean | null;
}
