/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.82
 */
import type { RecurrenceRuleSchema } from './recurrenceRuleSchema';

/**
 * Request body for updating a task.
 */
export interface TaskUpdate {
  title?: string | null;
  description?: string | null;
  domain_id?: number | null;
  parent_id?: number | null;
  duration_minutes?: number | null;
  impact?: number | null;
  clarity?: string | null;
  scheduled_date?: string | null;
  scheduled_time?: string | null;
  is_recurring?: boolean | null;
  recurrence_rule?: RecurrenceRuleSchema | null;
  recurrence_start?: string | null;
  recurrence_end?: string | null;
  position?: number | null;
}
