/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

/**
 * Single task's content for batch update.
 */
export interface TaskContentData {
  id: number;
  title: string;
  description?: string | null;
}
