/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.55.68
 */

/**
 * Response for task complete/uncomplete.
 */
export interface TaskCompleteResponse {
  status: string;
  task_id: number;
}
