/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */

/**
 * Response for task toggle-complete.

For recurring tasks, includes instance_id.
For non-recurring tasks, includes cascaded_subtask_ids.
 */
export interface TaskToggleCompleteResponse {
  status: string;
  task_id: number;
  completed: boolean;
  instance_id?: number | null;
  cascaded_subtask_ids?: number[] | null;
}
