/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

export type TodoistCallbackAuthTodoistCallbackGetParams = {
code?: string | null;
state?: string | null;
error?: string | null;
};
