/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

export type TodoistCallbackAuthTodoistCallbackGetParams = {
code?: string | null;
state?: string | null;
error?: string | null;
};
