/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

/**
 * Request body for toggle-complete with optional date.
 */
export interface ToggleCompleteRequest {
  target_date?: string | null;
}
