/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.72
 */

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}
