/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.4
 */

export interface WeekComparisonResponse {
  this_week: number;
  last_week: number;
  change_pct: number;
}
