/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */

export interface WeekComparisonResponse {
  this_week: number;
  last_week: number;
  change_pct: number;
}
