/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */

/**
 * Response from wipe operation.
 */
export interface WipeResponse {
  success: boolean;
  instances_deleted: number;
  tasks_deleted: number;
  domains_deleted: number;
}
