/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */

/**
 * Response model for wizard status.
 */
export interface WizardStatusResponse {
  completed: boolean;
  completed_at?: string | null;
}
