/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AnalyticsAnalyticsGetParams,
  HTTPValidationError
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Home page - redirect based on auth and wizard status, or show login.
 * @summary Index
 */
export const indexGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/`, method: 'GET', signal
    },
      );
    }
  



export const getIndexGetQueryKey = () => {
    return [
    `/`
    ] as const;
    }

    
export const getIndexGetQueryOptions = <TData = Awaited<ReturnType<typeof indexGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIndexGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof indexGet>>> = ({ signal }) => indexGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type IndexGetQueryResult = NonNullable<Awaited<ReturnType<typeof indexGet>>>
export type IndexGetQueryError = unknown


export function useIndexGet<TData = Awaited<ReturnType<typeof indexGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof indexGet>>,
          TError,
          Awaited<ReturnType<typeof indexGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useIndexGet<TData = Awaited<ReturnType<typeof indexGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof indexGet>>,
          TError,
          Awaited<ReturnType<typeof indexGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useIndexGet<TData = Awaited<ReturnType<typeof indexGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Index
 */

export function useIndexGet<TData = Awaited<ReturnType<typeof indexGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof indexGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getIndexGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Dashboard with task list grouped by domain and calendar events.
 * @summary Dashboard
 */
export const dashboardDashboardGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/dashboard`, method: 'GET', signal
    },
      );
    }
  



export const getDashboardDashboardGetQueryKey = () => {
    return [
    `/dashboard`
    ] as const;
    }

    
export const getDashboardDashboardGetQueryOptions = <TData = Awaited<ReturnType<typeof dashboardDashboardGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dashboardDashboardGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDashboardDashboardGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dashboardDashboardGet>>> = ({ signal }) => dashboardDashboardGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dashboardDashboardGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DashboardDashboardGetQueryResult = NonNullable<Awaited<ReturnType<typeof dashboardDashboardGet>>>
export type DashboardDashboardGetQueryError = unknown


export function useDashboardDashboardGet<TData = Awaited<ReturnType<typeof dashboardDashboardGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dashboardDashboardGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardDashboardGet>>,
          TError,
          Awaited<ReturnType<typeof dashboardDashboardGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDashboardDashboardGet<TData = Awaited<ReturnType<typeof dashboardDashboardGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dashboardDashboardGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dashboardDashboardGet>>,
          TError,
          Awaited<ReturnType<typeof dashboardDashboardGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDashboardDashboardGet<TData = Awaited<ReturnType<typeof dashboardDashboardGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dashboardDashboardGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Dashboard
 */

export function useDashboardDashboardGet<TData = Awaited<ReturnType<typeof dashboardDashboardGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dashboardDashboardGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDashboardDashboardGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Return just the task list HTML for HTMX partial updates.
 * @summary Task List Partial
 */
export const taskListPartialApiV1TaskListGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/api/v1/task-list`, method: 'GET', signal
    },
      );
    }
  



export const getTaskListPartialApiV1TaskListGetQueryKey = () => {
    return [
    `/api/v1/task-list`
    ] as const;
    }

    
export const getTaskListPartialApiV1TaskListGetQueryOptions = <TData = Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTaskListPartialApiV1TaskListGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>> = ({ signal }) => taskListPartialApiV1TaskListGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TaskListPartialApiV1TaskListGetQueryResult = NonNullable<Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>>
export type TaskListPartialApiV1TaskListGetQueryError = unknown


export function useTaskListPartialApiV1TaskListGet<TData = Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>,
          TError,
          Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTaskListPartialApiV1TaskListGet<TData = Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>,
          TError,
          Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTaskListPartialApiV1TaskListGet<TData = Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Task List Partial
 */

export function useTaskListPartialApiV1TaskListGet<TData = Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskListPartialApiV1TaskListGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTaskListPartialApiV1TaskListGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Return server-rendered HTML for a single task item.
 * @summary Task Item Partial
 */
export const taskItemPartialApiV1TaskItemTaskIdGet = (
    taskId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/api/v1/task-item/${taskId}`, method: 'GET', signal
    },
      );
    }
  



export const getTaskItemPartialApiV1TaskItemTaskIdGetQueryKey = (taskId: number,) => {
    return [
    `/api/v1/task-item/${taskId}`
    ] as const;
    }

    
export const getTaskItemPartialApiV1TaskItemTaskIdGetQueryOptions = <TData = Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError = HTTPValidationError>(taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTaskItemPartialApiV1TaskItemTaskIdGetQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>> = ({ signal }) => taskItemPartialApiV1TaskItemTaskIdGet(taskId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TaskItemPartialApiV1TaskItemTaskIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>>
export type TaskItemPartialApiV1TaskItemTaskIdGetQueryError = HTTPValidationError


export function useTaskItemPartialApiV1TaskItemTaskIdGet<TData = Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTaskItemPartialApiV1TaskItemTaskIdGet<TData = Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTaskItemPartialApiV1TaskItemTaskIdGet<TData = Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Task Item Partial
 */

export function useTaskItemPartialApiV1TaskItemTaskIdGet<TData = Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof taskItemPartialApiV1TaskItemTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTaskItemPartialApiV1TaskItemTaskIdGetQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Return deleted tasks HTML for HTMX.
 * @summary Deleted Tasks Partial
 */
export const deletedTasksPartialApiV1DeletedTasksGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/api/v1/deleted-tasks`, method: 'GET', signal
    },
      );
    }
  



export const getDeletedTasksPartialApiV1DeletedTasksGetQueryKey = () => {
    return [
    `/api/v1/deleted-tasks`
    ] as const;
    }

    
export const getDeletedTasksPartialApiV1DeletedTasksGetQueryOptions = <TData = Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeletedTasksPartialApiV1DeletedTasksGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>> = ({ signal }) => deletedTasksPartialApiV1DeletedTasksGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeletedTasksPartialApiV1DeletedTasksGetQueryResult = NonNullable<Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>>
export type DeletedTasksPartialApiV1DeletedTasksGetQueryError = unknown


export function useDeletedTasksPartialApiV1DeletedTasksGet<TData = Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>,
          TError,
          Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeletedTasksPartialApiV1DeletedTasksGet<TData = Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>,
          TError,
          Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeletedTasksPartialApiV1DeletedTasksGet<TData = Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Deleted Tasks Partial
 */

export function useDeletedTasksPartialApiV1DeletedTasksGet<TData = Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deletedTasksPartialApiV1DeletedTasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeletedTasksPartialApiV1DeletedTasksGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Return scheduled tasks HTML for HTMX.
 * @summary Scheduled Tasks Partial
 */
export const scheduledTasksPartialApiV1ScheduledTasksGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/api/v1/scheduled-tasks`, method: 'GET', signal
    },
      );
    }
  



export const getScheduledTasksPartialApiV1ScheduledTasksGetQueryKey = () => {
    return [
    `/api/v1/scheduled-tasks`
    ] as const;
    }

    
export const getScheduledTasksPartialApiV1ScheduledTasksGetQueryOptions = <TData = Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getScheduledTasksPartialApiV1ScheduledTasksGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>> = ({ signal }) => scheduledTasksPartialApiV1ScheduledTasksGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ScheduledTasksPartialApiV1ScheduledTasksGetQueryResult = NonNullable<Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>>
export type ScheduledTasksPartialApiV1ScheduledTasksGetQueryError = unknown


export function useScheduledTasksPartialApiV1ScheduledTasksGet<TData = Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>,
          TError,
          Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduledTasksPartialApiV1ScheduledTasksGet<TData = Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>,
          TError,
          Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useScheduledTasksPartialApiV1ScheduledTasksGet<TData = Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Scheduled Tasks Partial
 */

export function useScheduledTasksPartialApiV1ScheduledTasksGet<TData = Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof scheduledTasksPartialApiV1ScheduledTasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getScheduledTasksPartialApiV1ScheduledTasksGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Return completed tasks HTML for HTMX.
 * @summary Completed Tasks Partial
 */
export const completedTasksPartialApiV1CompletedTasksGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/api/v1/completed-tasks`, method: 'GET', signal
    },
      );
    }
  



export const getCompletedTasksPartialApiV1CompletedTasksGetQueryKey = () => {
    return [
    `/api/v1/completed-tasks`
    ] as const;
    }

    
export const getCompletedTasksPartialApiV1CompletedTasksGetQueryOptions = <TData = Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCompletedTasksPartialApiV1CompletedTasksGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>> = ({ signal }) => completedTasksPartialApiV1CompletedTasksGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CompletedTasksPartialApiV1CompletedTasksGetQueryResult = NonNullable<Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>>
export type CompletedTasksPartialApiV1CompletedTasksGetQueryError = unknown


export function useCompletedTasksPartialApiV1CompletedTasksGet<TData = Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>,
          TError,
          Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompletedTasksPartialApiV1CompletedTasksGet<TData = Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>,
          TError,
          Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCompletedTasksPartialApiV1CompletedTasksGet<TData = Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Completed Tasks Partial
 */

export function useCompletedTasksPartialApiV1CompletedTasksGet<TData = Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof completedTasksPartialApiV1CompletedTasksGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCompletedTasksPartialApiV1CompletedTasksGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Thoughts page - inbox tasks without a domain.
 * @summary Thoughts
 */
export const thoughtsThoughtsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/thoughts`, method: 'GET', signal
    },
      );
    }
  



export const getThoughtsThoughtsGetQueryKey = () => {
    return [
    `/thoughts`
    ] as const;
    }

    
export const getThoughtsThoughtsGetQueryOptions = <TData = Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getThoughtsThoughtsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof thoughtsThoughtsGet>>> = ({ signal }) => thoughtsThoughtsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ThoughtsThoughtsGetQueryResult = NonNullable<Awaited<ReturnType<typeof thoughtsThoughtsGet>>>
export type ThoughtsThoughtsGetQueryError = unknown


export function useThoughtsThoughtsGet<TData = Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof thoughtsThoughtsGet>>,
          TError,
          Awaited<ReturnType<typeof thoughtsThoughtsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useThoughtsThoughtsGet<TData = Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof thoughtsThoughtsGet>>,
          TError,
          Awaited<ReturnType<typeof thoughtsThoughtsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useThoughtsThoughtsGet<TData = Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Thoughts
 */

export function useThoughtsThoughtsGet<TData = Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof thoughtsThoughtsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getThoughtsThoughtsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Settings page - domains and calendar selection.
 * @summary Settings
 */
export const settingsSettingsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/settings`, method: 'GET', signal
    },
      );
    }
  



export const getSettingsSettingsGetQueryKey = () => {
    return [
    `/settings`
    ] as const;
    }

    
export const getSettingsSettingsGetQueryOptions = <TData = Awaited<ReturnType<typeof settingsSettingsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsSettingsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSettingsSettingsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof settingsSettingsGet>>> = ({ signal }) => settingsSettingsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof settingsSettingsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SettingsSettingsGetQueryResult = NonNullable<Awaited<ReturnType<typeof settingsSettingsGet>>>
export type SettingsSettingsGetQueryError = unknown


export function useSettingsSettingsGet<TData = Awaited<ReturnType<typeof settingsSettingsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsSettingsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsSettingsGet>>,
          TError,
          Awaited<ReturnType<typeof settingsSettingsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsSettingsGet<TData = Awaited<ReturnType<typeof settingsSettingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsSettingsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof settingsSettingsGet>>,
          TError,
          Awaited<ReturnType<typeof settingsSettingsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSettingsSettingsGet<TData = Awaited<ReturnType<typeof settingsSettingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsSettingsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Settings
 */

export function useSettingsSettingsGet<TData = Awaited<ReturnType<typeof settingsSettingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof settingsSettingsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSettingsSettingsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Analytics page - comprehensive stats dashboard.
 * @summary Analytics
 */
export const analyticsAnalyticsGet = (
    params?: AnalyticsAnalyticsGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/analytics`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getAnalyticsAnalyticsGetQueryKey = (params?: AnalyticsAnalyticsGetParams,) => {
    return [
    `/analytics`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getAnalyticsAnalyticsGetQueryOptions = <TData = Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError = HTTPValidationError>(params?: AnalyticsAnalyticsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAnalyticsAnalyticsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof analyticsAnalyticsGet>>> = ({ signal }) => analyticsAnalyticsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AnalyticsAnalyticsGetQueryResult = NonNullable<Awaited<ReturnType<typeof analyticsAnalyticsGet>>>
export type AnalyticsAnalyticsGetQueryError = HTTPValidationError


export function useAnalyticsAnalyticsGet<TData = Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError = HTTPValidationError>(
 params: undefined |  AnalyticsAnalyticsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof analyticsAnalyticsGet>>,
          TError,
          Awaited<ReturnType<typeof analyticsAnalyticsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAnalyticsAnalyticsGet<TData = Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError = HTTPValidationError>(
 params?: AnalyticsAnalyticsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof analyticsAnalyticsGet>>,
          TError,
          Awaited<ReturnType<typeof analyticsAnalyticsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAnalyticsAnalyticsGet<TData = Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError = HTTPValidationError>(
 params?: AnalyticsAnalyticsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Analytics
 */

export function useAnalyticsAnalyticsGet<TData = Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError = HTTPValidationError>(
 params?: AnalyticsAnalyticsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof analyticsAnalyticsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAnalyticsAnalyticsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Terms of Service page.
 * @summary Terms
 */
export const termsTermsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/terms`, method: 'GET', signal
    },
      );
    }
  



export const getTermsTermsGetQueryKey = () => {
    return [
    `/terms`
    ] as const;
    }

    
export const getTermsTermsGetQueryOptions = <TData = Awaited<ReturnType<typeof termsTermsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof termsTermsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTermsTermsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof termsTermsGet>>> = ({ signal }) => termsTermsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof termsTermsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TermsTermsGetQueryResult = NonNullable<Awaited<ReturnType<typeof termsTermsGet>>>
export type TermsTermsGetQueryError = unknown


export function useTermsTermsGet<TData = Awaited<ReturnType<typeof termsTermsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof termsTermsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof termsTermsGet>>,
          TError,
          Awaited<ReturnType<typeof termsTermsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTermsTermsGet<TData = Awaited<ReturnType<typeof termsTermsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof termsTermsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof termsTermsGet>>,
          TError,
          Awaited<ReturnType<typeof termsTermsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTermsTermsGet<TData = Awaited<ReturnType<typeof termsTermsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof termsTermsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Terms
 */

export function useTermsTermsGet<TData = Awaited<ReturnType<typeof termsTermsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof termsTermsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTermsTermsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Privacy Policy page.
 * @summary Privacy
 */
export const privacyPrivacyGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/privacy`, method: 'GET', signal
    },
      );
    }
  



export const getPrivacyPrivacyGetQueryKey = () => {
    return [
    `/privacy`
    ] as const;
    }

    
export const getPrivacyPrivacyGetQueryOptions = <TData = Awaited<ReturnType<typeof privacyPrivacyGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyPrivacyGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPrivacyPrivacyGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof privacyPrivacyGet>>> = ({ signal }) => privacyPrivacyGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof privacyPrivacyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PrivacyPrivacyGetQueryResult = NonNullable<Awaited<ReturnType<typeof privacyPrivacyGet>>>
export type PrivacyPrivacyGetQueryError = unknown


export function usePrivacyPrivacyGet<TData = Awaited<ReturnType<typeof privacyPrivacyGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyPrivacyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof privacyPrivacyGet>>,
          TError,
          Awaited<ReturnType<typeof privacyPrivacyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrivacyPrivacyGet<TData = Awaited<ReturnType<typeof privacyPrivacyGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyPrivacyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof privacyPrivacyGet>>,
          TError,
          Awaited<ReturnType<typeof privacyPrivacyGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePrivacyPrivacyGet<TData = Awaited<ReturnType<typeof privacyPrivacyGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyPrivacyGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Privacy
 */

export function usePrivacyPrivacyGet<TData = Awaited<ReturnType<typeof privacyPrivacyGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof privacyPrivacyGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPrivacyPrivacyGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * UI Component Showcase - for design review.
 * @summary Showcase
 */
export const showcaseShowcaseGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/showcase`, method: 'GET', signal
    },
      );
    }
  



export const getShowcaseShowcaseGetQueryKey = () => {
    return [
    `/showcase`
    ] as const;
    }

    
export const getShowcaseShowcaseGetQueryOptions = <TData = Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getShowcaseShowcaseGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof showcaseShowcaseGet>>> = ({ signal }) => showcaseShowcaseGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShowcaseShowcaseGetQueryResult = NonNullable<Awaited<ReturnType<typeof showcaseShowcaseGet>>>
export type ShowcaseShowcaseGetQueryError = unknown


export function useShowcaseShowcaseGet<TData = Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof showcaseShowcaseGet>>,
          TError,
          Awaited<ReturnType<typeof showcaseShowcaseGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowcaseShowcaseGet<TData = Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof showcaseShowcaseGet>>,
          TError,
          Awaited<ReturnType<typeof showcaseShowcaseGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShowcaseShowcaseGet<TData = Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Showcase
 */

export function useShowcaseShowcaseGet<TData = Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof showcaseShowcaseGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShowcaseShowcaseGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Mobile layout mockups - for testing layout options on phone.
 * @summary Mobile Mockups
 */
export const mobileMockupsMockupsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<string>(
      {url: `/mockups`, method: 'GET', signal
    },
      );
    }
  



export const getMobileMockupsMockupsGetQueryKey = () => {
    return [
    `/mockups`
    ] as const;
    }

    
export const getMobileMockupsMockupsGetQueryOptions = <TData = Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMobileMockupsMockupsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof mobileMockupsMockupsGet>>> = ({ signal }) => mobileMockupsMockupsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MobileMockupsMockupsGetQueryResult = NonNullable<Awaited<ReturnType<typeof mobileMockupsMockupsGet>>>
export type MobileMockupsMockupsGetQueryError = unknown


export function useMobileMockupsMockupsGet<TData = Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mobileMockupsMockupsGet>>,
          TError,
          Awaited<ReturnType<typeof mobileMockupsMockupsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMobileMockupsMockupsGet<TData = Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mobileMockupsMockupsGet>>,
          TError,
          Awaited<ReturnType<typeof mobileMockupsMockupsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMobileMockupsMockupsGet<TData = Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Mobile Mockups
 */

export function useMobileMockupsMockupsGet<TData = Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mobileMockupsMockupsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMobileMockupsMockupsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




