/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EncryptionSetupRequest,
  EncryptionSetupResponse,
  EncryptionStatusResponse,
  HTTPValidationError,
  PreferencesResponse,
  PreferencesUpdate
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Get current user's preferences (creates defaults if missing).
 * @summary Get Preferences
 */
export const getPreferencesApiV1PreferencesGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<PreferencesResponse>(
      {url: `/api/v1/preferences`, method: 'GET', signal
    },
      );
    }
  



export const getGetPreferencesApiV1PreferencesGetQueryKey = () => {
    return [
    `/api/v1/preferences`
    ] as const;
    }

    
export const getGetPreferencesApiV1PreferencesGetQueryOptions = <TData = Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPreferencesApiV1PreferencesGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>> = ({ signal }) => getPreferencesApiV1PreferencesGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPreferencesApiV1PreferencesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>>
export type GetPreferencesApiV1PreferencesGetQueryError = unknown


export function useGetPreferencesApiV1PreferencesGet<TData = Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>,
          TError,
          Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPreferencesApiV1PreferencesGet<TData = Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>,
          TError,
          Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPreferencesApiV1PreferencesGet<TData = Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Preferences
 */

export function useGetPreferencesApiV1PreferencesGet<TData = Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPreferencesApiV1PreferencesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPreferencesApiV1PreferencesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update current user's preferences.
 * @summary Update Preferences
 */
export const updatePreferencesApiV1PreferencesPut = (
    preferencesUpdate: PreferencesUpdate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<PreferencesResponse>(
      {url: `/api/v1/preferences`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: preferencesUpdate, signal
    },
      );
    }
  


export const getUpdatePreferencesApiV1PreferencesPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePreferencesApiV1PreferencesPut>>, TError,{data: PreferencesUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePreferencesApiV1PreferencesPut>>, TError,{data: PreferencesUpdate}, TContext> => {

const mutationKey = ['updatePreferencesApiV1PreferencesPut'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePreferencesApiV1PreferencesPut>>, {data: PreferencesUpdate}> = (props) => {
          const {data} = props ?? {};

          return  updatePreferencesApiV1PreferencesPut(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdatePreferencesApiV1PreferencesPutMutationResult = NonNullable<Awaited<ReturnType<typeof updatePreferencesApiV1PreferencesPut>>>
    export type UpdatePreferencesApiV1PreferencesPutMutationBody = PreferencesUpdate
    export type UpdatePreferencesApiV1PreferencesPutMutationError = HTTPValidationError

    /**
 * @summary Update Preferences
 */
export const useUpdatePreferencesApiV1PreferencesPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePreferencesApiV1PreferencesPut>>, TError,{data: PreferencesUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePreferencesApiV1PreferencesPut>>,
        TError,
        {data: PreferencesUpdate},
        TContext
      > => {
      return useMutation(getUpdatePreferencesApiV1PreferencesPutMutationOptions(options), queryClient);
    }
    /**
 * Get encryption status for current user.

Returns whether encryption is enabled and the salt (if enabled).
The salt is needed client-side to derive the decryption key.
 * @summary Get Encryption Status
 */
export const getEncryptionStatusApiV1PreferencesEncryptionGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<EncryptionStatusResponse>(
      {url: `/api/v1/preferences/encryption`, method: 'GET', signal
    },
      );
    }
  



export const getGetEncryptionStatusApiV1PreferencesEncryptionGetQueryKey = () => {
    return [
    `/api/v1/preferences/encryption`
    ] as const;
    }

    
export const getGetEncryptionStatusApiV1PreferencesEncryptionGetQueryOptions = <TData = Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEncryptionStatusApiV1PreferencesEncryptionGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>> = ({ signal }) => getEncryptionStatusApiV1PreferencesEncryptionGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEncryptionStatusApiV1PreferencesEncryptionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>>
export type GetEncryptionStatusApiV1PreferencesEncryptionGetQueryError = unknown


export function useGetEncryptionStatusApiV1PreferencesEncryptionGet<TData = Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>,
          TError,
          Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEncryptionStatusApiV1PreferencesEncryptionGet<TData = Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>,
          TError,
          Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEncryptionStatusApiV1PreferencesEncryptionGet<TData = Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Encryption Status
 */

export function useGetEncryptionStatusApiV1PreferencesEncryptionGet<TData = Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEncryptionStatusApiV1PreferencesEncryptionGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEncryptionStatusApiV1PreferencesEncryptionGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Set up E2E encryption for the user.

The client generates a salt and derives an encryption key from the passphrase.
The client encrypts a known test value ("WHENDOIST_ENCRYPTION_TEST") and sends
both the salt and encrypted test value to the server.

This endpoint stores the salt and test value, and marks encryption as enabled.
 * @summary Setup Encryption
 */
export const setupEncryptionApiV1PreferencesEncryptionSetupPost = (
    encryptionSetupRequest: EncryptionSetupRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<EncryptionSetupResponse>(
      {url: `/api/v1/preferences/encryption/setup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: encryptionSetupRequest, signal
    },
      );
    }
  


export const getSetupEncryptionApiV1PreferencesEncryptionSetupPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setupEncryptionApiV1PreferencesEncryptionSetupPost>>, TError,{data: EncryptionSetupRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof setupEncryptionApiV1PreferencesEncryptionSetupPost>>, TError,{data: EncryptionSetupRequest}, TContext> => {

const mutationKey = ['setupEncryptionApiV1PreferencesEncryptionSetupPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setupEncryptionApiV1PreferencesEncryptionSetupPost>>, {data: EncryptionSetupRequest}> = (props) => {
          const {data} = props ?? {};

          return  setupEncryptionApiV1PreferencesEncryptionSetupPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SetupEncryptionApiV1PreferencesEncryptionSetupPostMutationResult = NonNullable<Awaited<ReturnType<typeof setupEncryptionApiV1PreferencesEncryptionSetupPost>>>
    export type SetupEncryptionApiV1PreferencesEncryptionSetupPostMutationBody = EncryptionSetupRequest
    export type SetupEncryptionApiV1PreferencesEncryptionSetupPostMutationError = HTTPValidationError

    /**
 * @summary Setup Encryption
 */
export const useSetupEncryptionApiV1PreferencesEncryptionSetupPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setupEncryptionApiV1PreferencesEncryptionSetupPost>>, TError,{data: EncryptionSetupRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof setupEncryptionApiV1PreferencesEncryptionSetupPost>>,
        TError,
        {data: EncryptionSetupRequest},
        TContext
      > => {
      return useMutation(getSetupEncryptionApiV1PreferencesEncryptionSetupPostMutationOptions(options), queryClient);
    }
    /**
 * Disable E2E encryption for the user.

WARNING: This does NOT decrypt existing data. Encrypted data will remain
encrypted but unreadable without the original passphrase.

To properly disable encryption:
1. Export all data (backup)
2. Disable encryption
3. Import data back (unencrypted)
 * @summary Disable Encryption
 */
export const disableEncryptionApiV1PreferencesEncryptionDisablePost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<EncryptionSetupResponse>(
      {url: `/api/v1/preferences/encryption/disable`, method: 'POST', signal
    },
      );
    }
  


export const getDisableEncryptionApiV1PreferencesEncryptionDisablePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableEncryptionApiV1PreferencesEncryptionDisablePost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof disableEncryptionApiV1PreferencesEncryptionDisablePost>>, TError,void, TContext> => {

const mutationKey = ['disableEncryptionApiV1PreferencesEncryptionDisablePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disableEncryptionApiV1PreferencesEncryptionDisablePost>>, void> = () => {
          

          return  disableEncryptionApiV1PreferencesEncryptionDisablePost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DisableEncryptionApiV1PreferencesEncryptionDisablePostMutationResult = NonNullable<Awaited<ReturnType<typeof disableEncryptionApiV1PreferencesEncryptionDisablePost>>>
    
    export type DisableEncryptionApiV1PreferencesEncryptionDisablePostMutationError = unknown

    /**
 * @summary Disable Encryption
 */
export const useDisableEncryptionApiV1PreferencesEncryptionDisablePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableEncryptionApiV1PreferencesEncryptionDisablePost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disableEncryptionApiV1PreferencesEncryptionDisablePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDisableEncryptionApiV1PreferencesEncryptionDisablePostMutationOptions(options), queryClient);
    }
    