/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationOptionsResponse,
  AuthenticationVerifyRequest,
  AuthenticationVerifyResponse,
  DeletePasskeyResponse,
  HTTPValidationError,
  PasskeyListResponse,
  RegistrationOptionsResponse,
  RegistrationVerifyRequest,
  RegistrationVerifyResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Get WebAuthn registration options for creating a new passkey.

The browser uses these options with navigator.credentials.create().
 * @summary Get Registration Options
 */
export const getRegistrationOptionsApiV1PasskeysRegisterOptionsPost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<RegistrationOptionsResponse>(
      {url: `/api/v1/passkeys/register/options`, method: 'POST', signal
    },
      );
    }
  


export const getGetRegistrationOptionsApiV1PasskeysRegisterOptionsPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getRegistrationOptionsApiV1PasskeysRegisterOptionsPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getRegistrationOptionsApiV1PasskeysRegisterOptionsPost>>, TError,void, TContext> => {

const mutationKey = ['getRegistrationOptionsApiV1PasskeysRegisterOptionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getRegistrationOptionsApiV1PasskeysRegisterOptionsPost>>, void> = () => {
          

          return  getRegistrationOptionsApiV1PasskeysRegisterOptionsPost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetRegistrationOptionsApiV1PasskeysRegisterOptionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof getRegistrationOptionsApiV1PasskeysRegisterOptionsPost>>>
    
    export type GetRegistrationOptionsApiV1PasskeysRegisterOptionsPostMutationError = unknown

    /**
 * @summary Get Registration Options
 */
export const useGetRegistrationOptionsApiV1PasskeysRegisterOptionsPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getRegistrationOptionsApiV1PasskeysRegisterOptionsPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getRegistrationOptionsApiV1PasskeysRegisterOptionsPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetRegistrationOptionsApiV1PasskeysRegisterOptionsPostMutationOptions(options), queryClient);
    }
    /**
 * Verify the WebAuthn registration response and store the passkey.

After navigator.credentials.create() returns, the client sends the
credential along with the PRF salt and encrypted test value.
 * @summary Verify Registration
 */
export const verifyRegistrationApiV1PasskeysRegisterVerifyPost = (
    registrationVerifyRequest: RegistrationVerifyRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<RegistrationVerifyResponse>(
      {url: `/api/v1/passkeys/register/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registrationVerifyRequest, signal
    },
      );
    }
  


export const getVerifyRegistrationApiV1PasskeysRegisterVerifyPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyRegistrationApiV1PasskeysRegisterVerifyPost>>, TError,{data: RegistrationVerifyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof verifyRegistrationApiV1PasskeysRegisterVerifyPost>>, TError,{data: RegistrationVerifyRequest}, TContext> => {

const mutationKey = ['verifyRegistrationApiV1PasskeysRegisterVerifyPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyRegistrationApiV1PasskeysRegisterVerifyPost>>, {data: RegistrationVerifyRequest}> = (props) => {
          const {data} = props ?? {};

          return  verifyRegistrationApiV1PasskeysRegisterVerifyPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyRegistrationApiV1PasskeysRegisterVerifyPostMutationResult = NonNullable<Awaited<ReturnType<typeof verifyRegistrationApiV1PasskeysRegisterVerifyPost>>>
    export type VerifyRegistrationApiV1PasskeysRegisterVerifyPostMutationBody = RegistrationVerifyRequest
    export type VerifyRegistrationApiV1PasskeysRegisterVerifyPostMutationError = HTTPValidationError

    /**
 * @summary Verify Registration
 */
export const useVerifyRegistrationApiV1PasskeysRegisterVerifyPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyRegistrationApiV1PasskeysRegisterVerifyPost>>, TError,{data: RegistrationVerifyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyRegistrationApiV1PasskeysRegisterVerifyPost>>,
        TError,
        {data: RegistrationVerifyRequest},
        TContext
      > => {
      return useMutation(getVerifyRegistrationApiV1PasskeysRegisterVerifyPostMutationOptions(options), queryClient);
    }
    /**
 * Get WebAuthn authentication options for unlocking with a passkey.

Also returns the PRF salt and test value for the first passkey.
The browser uses these options with navigator.credentials.get().
 * @summary Get Authentication Options
 */
export const getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<AuthenticationOptionsResponse>(
      {url: `/api/v1/passkeys/authenticate/options`, method: 'POST', signal
    },
      );
    }
  


export const getGetAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost>>, TError,void, TContext> => {

const mutationKey = ['getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost>>, void> = () => {
          

          return  getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type GetAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost>>>
    
    export type GetAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPostMutationError = unknown

    /**
 * @summary Get Authentication Options
 */
export const useGetAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetAuthenticationOptionsApiV1PasskeysAuthenticateOptionsPostMutationOptions(options), queryClient);
    }
    /**
 * Verify the WebAuthn authentication response.

Returns the PRF salt and wrapped key for the authenticated passkey.
The client unwraps this to get the master encryption key.
 * @summary Verify Authentication
 */
export const verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost = (
    authenticationVerifyRequest: AuthenticationVerifyRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AuthenticationVerifyResponse>(
      {url: `/api/v1/passkeys/authenticate/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authenticationVerifyRequest, signal
    },
      );
    }
  


export const getVerifyAuthenticationApiV1PasskeysAuthenticateVerifyPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost>>, TError,{data: AuthenticationVerifyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost>>, TError,{data: AuthenticationVerifyRequest}, TContext> => {

const mutationKey = ['verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost>>, {data: AuthenticationVerifyRequest}> = (props) => {
          const {data} = props ?? {};

          return  verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyAuthenticationApiV1PasskeysAuthenticateVerifyPostMutationResult = NonNullable<Awaited<ReturnType<typeof verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost>>>
    export type VerifyAuthenticationApiV1PasskeysAuthenticateVerifyPostMutationBody = AuthenticationVerifyRequest
    export type VerifyAuthenticationApiV1PasskeysAuthenticateVerifyPostMutationError = HTTPValidationError

    /**
 * @summary Verify Authentication
 */
export const useVerifyAuthenticationApiV1PasskeysAuthenticateVerifyPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost>>, TError,{data: AuthenticationVerifyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyAuthenticationApiV1PasskeysAuthenticateVerifyPost>>,
        TError,
        {data: AuthenticationVerifyRequest},
        TContext
      > => {
      return useMutation(getVerifyAuthenticationApiV1PasskeysAuthenticateVerifyPostMutationOptions(options), queryClient);
    }
    /**
 * Get PRF data for a specific credential ID.

This is used when the browser already knows which credential was used
and needs to look up the corresponding PRF salt and wrapped key.
 * @summary Get Passkey By Credential
 */
export const getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet = (
    credentialId: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<unknown>(
      {url: `/api/v1/passkeys/by-credential/${credentialId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGetQueryKey = (credentialId: string,) => {
    return [
    `/api/v1/passkeys/by-credential/${credentialId}`
    ] as const;
    }

    
export const getGetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError = HTTPValidationError>(credentialId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGetQueryKey(credentialId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>> = ({ signal }) => getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet(credentialId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(credentialId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>>
export type GetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGetQueryError = HTTPValidationError


export function useGetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet<TData = Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError = HTTPValidationError>(
 credentialId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>,
          TError,
          Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet<TData = Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError = HTTPValidationError>(
 credentialId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>,
          TError,
          Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet<TData = Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError = HTTPValidationError>(
 credentialId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Passkey By Credential
 */

export function useGetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet<TData = Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError = HTTPValidationError>(
 credentialId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPasskeyByCredentialApiV1PasskeysByCredentialCredentialIdGetQueryOptions(credentialId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * List all passkeys for the current user.
 * @summary List Passkeys
 */
export const listPasskeysApiV1PasskeysGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<PasskeyListResponse>(
      {url: `/api/v1/passkeys`, method: 'GET', signal
    },
      );
    }
  



export const getListPasskeysApiV1PasskeysGetQueryKey = () => {
    return [
    `/api/v1/passkeys`
    ] as const;
    }

    
export const getListPasskeysApiV1PasskeysGetQueryOptions = <TData = Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPasskeysApiV1PasskeysGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>> = ({ signal }) => listPasskeysApiV1PasskeysGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPasskeysApiV1PasskeysGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>>
export type ListPasskeysApiV1PasskeysGetQueryError = unknown


export function useListPasskeysApiV1PasskeysGet<TData = Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>,
          TError,
          Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPasskeysApiV1PasskeysGet<TData = Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>,
          TError,
          Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPasskeysApiV1PasskeysGet<TData = Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Passkeys
 */

export function useListPasskeysApiV1PasskeysGet<TData = Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPasskeysApiV1PasskeysGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPasskeysApiV1PasskeysGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete a passkey.

Note: Cannot delete the last passkey if no passphrase fallback is configured.
 * @summary Delete Passkey
 */
export const deletePasskeyApiV1PasskeysPasskeyIdDelete = (
    passkeyId: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<DeletePasskeyResponse>(
      {url: `/api/v1/passkeys/${passkeyId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeletePasskeyApiV1PasskeysPasskeyIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePasskeyApiV1PasskeysPasskeyIdDelete>>, TError,{passkeyId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePasskeyApiV1PasskeysPasskeyIdDelete>>, TError,{passkeyId: number}, TContext> => {

const mutationKey = ['deletePasskeyApiV1PasskeysPasskeyIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePasskeyApiV1PasskeysPasskeyIdDelete>>, {passkeyId: number}> = (props) => {
          const {passkeyId} = props ?? {};

          return  deletePasskeyApiV1PasskeysPasskeyIdDelete(passkeyId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePasskeyApiV1PasskeysPasskeyIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deletePasskeyApiV1PasskeysPasskeyIdDelete>>>
    
    export type DeletePasskeyApiV1PasskeysPasskeyIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Passkey
 */
export const useDeletePasskeyApiV1PasskeysPasskeyIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePasskeyApiV1PasskeysPasskeyIdDelete>>, TError,{passkeyId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePasskeyApiV1PasskeysPasskeyIdDelete>>,
        TError,
        {passkeyId: number},
        TContext
      > => {
      return useMutation(getDeletePasskeyApiV1PasskeysPasskeyIdDeleteMutationOptions(options), queryClient);
    }
    