/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.48.8
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  WizardActionResponse,
  WizardStatusResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Check if wizard has been completed.
 * @summary Get Wizard Status
 */
export const getWizardStatusApiV1WizardStatusGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<WizardStatusResponse>(
      {url: `/api/v1/wizard/status`, method: 'GET', signal
    },
      );
    }
  



export const getGetWizardStatusApiV1WizardStatusGetQueryKey = () => {
    return [
    `/api/v1/wizard/status`
    ] as const;
    }

    
export const getGetWizardStatusApiV1WizardStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWizardStatusApiV1WizardStatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>> = ({ signal }) => getWizardStatusApiV1WizardStatusGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWizardStatusApiV1WizardStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>>
export type GetWizardStatusApiV1WizardStatusGetQueryError = unknown


export function useGetWizardStatusApiV1WizardStatusGet<TData = Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWizardStatusApiV1WizardStatusGet<TData = Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWizardStatusApiV1WizardStatusGet<TData = Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Wizard Status
 */

export function useGetWizardStatusApiV1WizardStatusGet<TData = Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWizardStatusApiV1WizardStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWizardStatusApiV1WizardStatusGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Mark wizard as completed.
 * @summary Complete Wizard
 */
export const completeWizardApiV1WizardCompletePost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<WizardActionResponse>(
      {url: `/api/v1/wizard/complete`, method: 'POST', signal
    },
      );
    }
  


export const getCompleteWizardApiV1WizardCompletePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeWizardApiV1WizardCompletePost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof completeWizardApiV1WizardCompletePost>>, TError,void, TContext> => {

const mutationKey = ['completeWizardApiV1WizardCompletePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof completeWizardApiV1WizardCompletePost>>, void> = () => {
          

          return  completeWizardApiV1WizardCompletePost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CompleteWizardApiV1WizardCompletePostMutationResult = NonNullable<Awaited<ReturnType<typeof completeWizardApiV1WizardCompletePost>>>
    
    export type CompleteWizardApiV1WizardCompletePostMutationError = unknown

    /**
 * @summary Complete Wizard
 */
export const useCompleteWizardApiV1WizardCompletePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof completeWizardApiV1WizardCompletePost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof completeWizardApiV1WizardCompletePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getCompleteWizardApiV1WizardCompletePostMutationOptions(options), queryClient);
    }
    /**
 * Reset wizard to allow re-running.
 * @summary Reset Wizard
 */
export const resetWizardApiV1WizardResetPost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<WizardActionResponse>(
      {url: `/api/v1/wizard/reset`, method: 'POST', signal
    },
      );
    }
  


export const getResetWizardApiV1WizardResetPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetWizardApiV1WizardResetPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof resetWizardApiV1WizardResetPost>>, TError,void, TContext> => {

const mutationKey = ['resetWizardApiV1WizardResetPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetWizardApiV1WizardResetPost>>, void> = () => {
          

          return  resetWizardApiV1WizardResetPost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ResetWizardApiV1WizardResetPostMutationResult = NonNullable<Awaited<ReturnType<typeof resetWizardApiV1WizardResetPost>>>
    
    export type ResetWizardApiV1WizardResetPostMutationError = unknown

    /**
 * @summary Reset Wizard
 */
export const useResetWizardApiV1WizardResetPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetWizardApiV1WizardResetPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetWizardApiV1WizardResetPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getResetWizardApiV1WizardResetPostMutationOptions(options), queryClient);
    }
    