/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * OpenAPI spec version: 0.54.5
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AnalyticsResponse,
  GetAnalyticsApiV1AnalyticsGetParams,
  GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams,
  HTTPValidationError,
  RecentCompletionItem
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Return comprehensive analytics data for the specified time range.
 * @summary Get Analytics
 */
export const getAnalyticsApiV1AnalyticsGet = (
    params?: GetAnalyticsApiV1AnalyticsGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AnalyticsResponse>(
      {url: `/api/v1/analytics`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAnalyticsApiV1AnalyticsGetQueryKey = (params?: GetAnalyticsApiV1AnalyticsGetParams,) => {
    return [
    `/api/v1/analytics`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAnalyticsApiV1AnalyticsGetQueryOptions = <TData = Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError = HTTPValidationError>(params?: GetAnalyticsApiV1AnalyticsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsApiV1AnalyticsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>> = ({ signal }) => getAnalyticsApiV1AnalyticsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticsApiV1AnalyticsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>>
export type GetAnalyticsApiV1AnalyticsGetQueryError = HTTPValidationError


export function useGetAnalyticsApiV1AnalyticsGet<TData = Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetAnalyticsApiV1AnalyticsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsApiV1AnalyticsGet<TData = Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError = HTTPValidationError>(
 params?: GetAnalyticsApiV1AnalyticsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsApiV1AnalyticsGet<TData = Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError = HTTPValidationError>(
 params?: GetAnalyticsApiV1AnalyticsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Analytics
 */

export function useGetAnalyticsApiV1AnalyticsGet<TData = Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError = HTTPValidationError>(
 params?: GetAnalyticsApiV1AnalyticsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsApiV1AnalyticsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalyticsApiV1AnalyticsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Return most recently completed tasks.
 * @summary Get Recent Completions
 */
export const getRecentCompletionsApiV1AnalyticsRecentCompletionsGet = (
    params?: GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<RecentCompletionItem[]>(
      {url: `/api/v1/analytics/recent-completions`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetRecentCompletionsApiV1AnalyticsRecentCompletionsGetQueryKey = (params?: GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams,) => {
    return [
    `/api/v1/analytics/recent-completions`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetRecentCompletionsApiV1AnalyticsRecentCompletionsGetQueryOptions = <TData = Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError = HTTPValidationError>(params?: GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecentCompletionsApiV1AnalyticsRecentCompletionsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>> = ({ signal }) => getRecentCompletionsApiV1AnalyticsRecentCompletionsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>>
export type GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetQueryError = HTTPValidationError


export function useGetRecentCompletionsApiV1AnalyticsRecentCompletionsGet<TData = Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError = HTTPValidationError>(
 params: undefined |  GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>,
          TError,
          Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentCompletionsApiV1AnalyticsRecentCompletionsGet<TData = Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError = HTTPValidationError>(
 params?: GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>,
          TError,
          Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecentCompletionsApiV1AnalyticsRecentCompletionsGet<TData = Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError = HTTPValidationError>(
 params?: GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Recent Completions
 */

export function useGetRecentCompletionsApiV1AnalyticsRecentCompletionsGet<TData = Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError = HTTPValidationError>(
 params?: GetRecentCompletionsApiV1AnalyticsRecentCompletionsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecentCompletionsApiV1AnalyticsRecentCompletionsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecentCompletionsApiV1AnalyticsRecentCompletionsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




