/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.57.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActivityLogEntry,
  ActivityLogResponse,
  GetTaskActivityApiV1ActivityTaskTaskIdGetParams,
  GetUserActivityApiV1ActivityGetParams,
  HTTPValidationError
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Get activity log for a specific task (includes instance events).
 * @summary Get Task Activity
 */
export const getTaskActivityApiV1ActivityTaskTaskIdGet = (
    taskId: number,
    params?: GetTaskActivityApiV1ActivityTaskTaskIdGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ActivityLogEntry[]>(
      {url: `/api/v1/activity/task/${taskId}`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetTaskActivityApiV1ActivityTaskTaskIdGetQueryKey = (taskId: number,
    params?: GetTaskActivityApiV1ActivityTaskTaskIdGetParams,) => {
    return [
    `/api/v1/activity/task/${taskId}`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetTaskActivityApiV1ActivityTaskTaskIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError = HTTPValidationError>(taskId: number,
    params?: GetTaskActivityApiV1ActivityTaskTaskIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskActivityApiV1ActivityTaskTaskIdGetQueryKey(taskId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>> = ({ signal }) => getTaskActivityApiV1ActivityTaskTaskIdGet(taskId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskActivityApiV1ActivityTaskTaskIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>>
export type GetTaskActivityApiV1ActivityTaskTaskIdGetQueryError = HTTPValidationError


export function useGetTaskActivityApiV1ActivityTaskTaskIdGet<TData = Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number,
    params: undefined |  GetTaskActivityApiV1ActivityTaskTaskIdGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskActivityApiV1ActivityTaskTaskIdGet<TData = Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number,
    params?: GetTaskActivityApiV1ActivityTaskTaskIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskActivityApiV1ActivityTaskTaskIdGet<TData = Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number,
    params?: GetTaskActivityApiV1ActivityTaskTaskIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Task Activity
 */

export function useGetTaskActivityApiV1ActivityTaskTaskIdGet<TData = Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number,
    params?: GetTaskActivityApiV1ActivityTaskTaskIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskActivityApiV1ActivityTaskTaskIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskActivityApiV1ActivityTaskTaskIdGetQueryOptions(taskId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get activity log for the current user (paginated, all events).
 * @summary Get User Activity
 */
export const getUserActivityApiV1ActivityGet = (
    params?: GetUserActivityApiV1ActivityGetParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ActivityLogResponse>(
      {url: `/api/v1/activity`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetUserActivityApiV1ActivityGetQueryKey = (params?: GetUserActivityApiV1ActivityGetParams,) => {
    return [
    `/api/v1/activity`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUserActivityApiV1ActivityGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError = HTTPValidationError>(params?: GetUserActivityApiV1ActivityGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivityApiV1ActivityGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>> = ({ signal }) => getUserActivityApiV1ActivityGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserActivityApiV1ActivityGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>>
export type GetUserActivityApiV1ActivityGetQueryError = HTTPValidationError


export function useGetUserActivityApiV1ActivityGet<TData = Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError = HTTPValidationError>(
 params: undefined |  GetUserActivityApiV1ActivityGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>,
          TError,
          Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivityApiV1ActivityGet<TData = Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError = HTTPValidationError>(
 params?: GetUserActivityApiV1ActivityGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>,
          TError,
          Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivityApiV1ActivityGet<TData = Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError = HTTPValidationError>(
 params?: GetUserActivityApiV1ActivityGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Activity
 */

export function useGetUserActivityApiV1ActivityGet<TData = Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError = HTTPValidationError>(
 params?: GetUserActivityApiV1ActivityGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivityApiV1ActivityGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserActivityApiV1ActivityGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




