/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.48.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppRoutersImportDataImportResponse,
  HTTPValidationError,
  ImportOptions,
  ImportPreviewResponse,
  WipeResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Delete all tasks and domains for the current user.

This is a destructive operation for testing purposes.
No external service connection required.
 * @summary Wipe User Data
 */
export const wipeUserDataApiV1ImportWipePost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<WipeResponse>(
      {url: `/api/v1/import/wipe`, method: 'POST', signal
    },
      );
    }
  


export const getWipeUserDataApiV1ImportWipePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof wipeUserDataApiV1ImportWipePost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof wipeUserDataApiV1ImportWipePost>>, TError,void, TContext> => {

const mutationKey = ['wipeUserDataApiV1ImportWipePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof wipeUserDataApiV1ImportWipePost>>, void> = () => {
          

          return  wipeUserDataApiV1ImportWipePost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type WipeUserDataApiV1ImportWipePostMutationResult = NonNullable<Awaited<ReturnType<typeof wipeUserDataApiV1ImportWipePost>>>
    
    export type WipeUserDataApiV1ImportWipePostMutationError = unknown

    /**
 * @summary Wipe User Data
 */
export const useWipeUserDataApiV1ImportWipePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof wipeUserDataApiV1ImportWipePost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof wipeUserDataApiV1ImportWipePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getWipeUserDataApiV1ImportWipePostMutationOptions(options), queryClient);
    }
    /**
 * Preview what will be imported from Todoist.

Returns counts and project list without actually importing anything.
 * @summary Preview Todoist Import
 */
export const previewTodoistImportApiV1ImportTodoistPreviewGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<ImportPreviewResponse>(
      {url: `/api/v1/import/todoist/preview`, method: 'GET', signal
    },
      );
    }
  



export const getPreviewTodoistImportApiV1ImportTodoistPreviewGetQueryKey = () => {
    return [
    `/api/v1/import/todoist/preview`
    ] as const;
    }

    
export const getPreviewTodoistImportApiV1ImportTodoistPreviewGetQueryOptions = <TData = Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewTodoistImportApiV1ImportTodoistPreviewGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>> = ({ signal }) => previewTodoistImportApiV1ImportTodoistPreviewGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PreviewTodoistImportApiV1ImportTodoistPreviewGetQueryResult = NonNullable<Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>>
export type PreviewTodoistImportApiV1ImportTodoistPreviewGetQueryError = unknown


export function usePreviewTodoistImportApiV1ImportTodoistPreviewGet<TData = Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>,
          TError,
          Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewTodoistImportApiV1ImportTodoistPreviewGet<TData = Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>,
          TError,
          Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePreviewTodoistImportApiV1ImportTodoistPreviewGet<TData = Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Preview Todoist Import
 */

export function usePreviewTodoistImportApiV1ImportTodoistPreviewGet<TData = Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof previewTodoistImportApiV1ImportTodoistPreviewGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPreviewTodoistImportApiV1ImportTodoistPreviewGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Import all projects and tasks from connected Todoist account.

Creates domains from Todoist projects and tasks with their attributes.
Skips items that have already been imported (tracked by external_id).
 * @summary Import From Todoist
 */
export const importFromTodoistApiV1ImportTodoistPost = (
    importOptionsNull: ImportOptions | null,
 signal?: AbortSignal
) => {
      
      
      return apiClient<AppRoutersImportDataImportResponse>(
      {url: `/api/v1/import/todoist`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: importOptionsNull, signal
    },
      );
    }
  


export const getImportFromTodoistApiV1ImportTodoistPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importFromTodoistApiV1ImportTodoistPost>>, TError,{data: ImportOptions | null}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof importFromTodoistApiV1ImportTodoistPost>>, TError,{data: ImportOptions | null}, TContext> => {

const mutationKey = ['importFromTodoistApiV1ImportTodoistPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importFromTodoistApiV1ImportTodoistPost>>, {data: ImportOptions | null}> = (props) => {
          const {data} = props ?? {};

          return  importFromTodoistApiV1ImportTodoistPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ImportFromTodoistApiV1ImportTodoistPostMutationResult = NonNullable<Awaited<ReturnType<typeof importFromTodoistApiV1ImportTodoistPost>>>
    export type ImportFromTodoistApiV1ImportTodoistPostMutationBody = ImportOptions | null
    export type ImportFromTodoistApiV1ImportTodoistPostMutationError = HTTPValidationError

    /**
 * @summary Import From Todoist
 */
export const useImportFromTodoistApiV1ImportTodoistPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importFromTodoistApiV1ImportTodoistPost>>, TError,{data: ImportOptions | null}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importFromTodoistApiV1ImportTodoistPost>>,
        TError,
        {data: ImportOptions | null},
        TContext
      > => {
      return useMutation(getImportFromTodoistApiV1ImportTodoistPostMutationOptions(options), queryClient);
    }
    