/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Whendoist
 * WHEN do I do my tasks?
 * OpenAPI spec version: 0.47.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkSyncResponse,
  HTTPValidationError,
  SyncDisableRequest,
  SyncDisableResponse,
  SyncEnableResponse,
  SyncStatusResponse
} from '../../model';

import { apiClient } from '../../../lib/api-client';




/**
 * Get current Google Calendar sync status.
 * @summary Get Sync Status
 */
export const getSyncStatusApiV1GcalSyncStatusGet = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<SyncStatusResponse>(
      {url: `/api/v1/gcal-sync/status`, method: 'GET', signal
    },
      );
    }
  



export const getGetSyncStatusApiV1GcalSyncStatusGetQueryKey = () => {
    return [
    `/api/v1/gcal-sync/status`
    ] as const;
    }

    
export const getGetSyncStatusApiV1GcalSyncStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSyncStatusApiV1GcalSyncStatusGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>> = ({ signal }) => getSyncStatusApiV1GcalSyncStatusGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSyncStatusApiV1GcalSyncStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>>
export type GetSyncStatusApiV1GcalSyncStatusGetQueryError = unknown


export function useGetSyncStatusApiV1GcalSyncStatusGet<TData = Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSyncStatusApiV1GcalSyncStatusGet<TData = Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSyncStatusApiV1GcalSyncStatusGet<TData = Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Sync Status
 */

export function useGetSyncStatusApiV1GcalSyncStatusGet<TData = Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncStatusApiV1GcalSyncStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSyncStatusApiV1GcalSyncStatusGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Enable Google Calendar sync.

If the user's token doesn't have write scope, returns a re-auth URL.
If scope is OK, creates the "Whendoist" calendar and runs initial sync.
 * @summary Enable Sync
 */
export const enableSyncApiV1GcalSyncEnablePost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<SyncEnableResponse>(
      {url: `/api/v1/gcal-sync/enable`, method: 'POST', signal
    },
      );
    }
  


export const getEnableSyncApiV1GcalSyncEnablePostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableSyncApiV1GcalSyncEnablePost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof enableSyncApiV1GcalSyncEnablePost>>, TError,void, TContext> => {

const mutationKey = ['enableSyncApiV1GcalSyncEnablePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enableSyncApiV1GcalSyncEnablePost>>, void> = () => {
          

          return  enableSyncApiV1GcalSyncEnablePost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EnableSyncApiV1GcalSyncEnablePostMutationResult = NonNullable<Awaited<ReturnType<typeof enableSyncApiV1GcalSyncEnablePost>>>
    
    export type EnableSyncApiV1GcalSyncEnablePostMutationError = unknown

    /**
 * @summary Enable Sync
 */
export const useEnableSyncApiV1GcalSyncEnablePost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enableSyncApiV1GcalSyncEnablePost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enableSyncApiV1GcalSyncEnablePost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getEnableSyncApiV1GcalSyncEnablePostMutationOptions(options), queryClient);
    }
    /**
 * Disable Google Calendar sync. Optionally delete all synced events.
 * @summary Disable Sync
 */
export const disableSyncApiV1GcalSyncDisablePost = (
    syncDisableRequestNull: SyncDisableRequest | null,
 signal?: AbortSignal
) => {
      
      
      return apiClient<SyncDisableResponse>(
      {url: `/api/v1/gcal-sync/disable`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: syncDisableRequestNull, signal
    },
      );
    }
  


export const getDisableSyncApiV1GcalSyncDisablePostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableSyncApiV1GcalSyncDisablePost>>, TError,{data: SyncDisableRequest | null}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof disableSyncApiV1GcalSyncDisablePost>>, TError,{data: SyncDisableRequest | null}, TContext> => {

const mutationKey = ['disableSyncApiV1GcalSyncDisablePost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disableSyncApiV1GcalSyncDisablePost>>, {data: SyncDisableRequest | null}> = (props) => {
          const {data} = props ?? {};

          return  disableSyncApiV1GcalSyncDisablePost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DisableSyncApiV1GcalSyncDisablePostMutationResult = NonNullable<Awaited<ReturnType<typeof disableSyncApiV1GcalSyncDisablePost>>>
    export type DisableSyncApiV1GcalSyncDisablePostMutationBody = SyncDisableRequest | null
    export type DisableSyncApiV1GcalSyncDisablePostMutationError = HTTPValidationError

    /**
 * @summary Disable Sync
 */
export const useDisableSyncApiV1GcalSyncDisablePost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disableSyncApiV1GcalSyncDisablePost>>, TError,{data: SyncDisableRequest | null}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disableSyncApiV1GcalSyncDisablePost>>,
        TError,
        {data: SyncDisableRequest | null},
        TContext
      > => {
      return useMutation(getDisableSyncApiV1GcalSyncDisablePostMutationOptions(options), queryClient);
    }
    /**
 * Trigger a full re-sync of all tasks (runs in background).
 * @summary Full Sync
 */
export const fullSyncApiV1GcalSyncFullSyncPost = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<BulkSyncResponse>(
      {url: `/api/v1/gcal-sync/full-sync`, method: 'POST', signal
    },
      );
    }
  


export const getFullSyncApiV1GcalSyncFullSyncPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fullSyncApiV1GcalSyncFullSyncPost>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof fullSyncApiV1GcalSyncFullSyncPost>>, TError,void, TContext> => {

const mutationKey = ['fullSyncApiV1GcalSyncFullSyncPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof fullSyncApiV1GcalSyncFullSyncPost>>, void> = () => {
          

          return  fullSyncApiV1GcalSyncFullSyncPost()
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FullSyncApiV1GcalSyncFullSyncPostMutationResult = NonNullable<Awaited<ReturnType<typeof fullSyncApiV1GcalSyncFullSyncPost>>>
    
    export type FullSyncApiV1GcalSyncFullSyncPostMutationError = unknown

    /**
 * @summary Full Sync
 */
export const useFullSyncApiV1GcalSyncFullSyncPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof fullSyncApiV1GcalSyncFullSyncPost>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof fullSyncApiV1GcalSyncFullSyncPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getFullSyncApiV1GcalSyncFullSyncPostMutationOptions(options), queryClient);
    }
    